### ISSUE TITLE
SubtypingChecker: Exception: java.lang.NullPointerException: Cannot read the array length because "a" is null

### ISSUE THREAD

**Issue by siudeks** [typetools/checker-framework#5837] opened 2023-05-04 11:28 UTC
As a developer I would like to use annotations to introduce strongly-typed checks based on annotations
e.g. as described here https://stackoverflow.com/questions/65623179/how-to-implement-domain-strong-typing-using-java-annotations

At the starting point I am not able to create any working maven-based example to see how SubtypingChecker works
Issue reproduction: https://github.com/siudeks/repro/tree/checker_framework_maven_subtyping

Instead of see any working check, I have exception
Exception: java.lang.NullPointerException: Cannot read the array length because "a" is null; java.lang.NullPointerException: Cannot read the array length because "a" is null

I would really apprectate any help what how write to achieve strongly typed checks, based on annotationed strings like @Email, @Address etcv.

**Comment by smillst** [comment] 2023-05-17 17:31
Thanks for reporting this.  The problem is that the argument to `-AqualDirs` must be a  fully-qualified path.   It' can't include things like `../`.   However the Checker Framework should provide a better error message in this case, I'll fix that.

**Comment by smillst** [comment] 2023-05-17 19:18
Actually if you change `<arg>-AqualDirs=../../module1/target</arg>` to  `<arg>-AqualDirs=../module1/target/classes</arg>` the crash will go away.  (I'll still add a better error message.) But you will get the following error:
```
 error: SubtypingChecker: could not load class for annotation: com.example.demo.qual.Address. Ensure that it is a type annotation and your classpath is correct.
```

You can fix that by putting the new qualifiers on the processor path:
```
                                       <annotationProcessorPaths>
                                              <path>
                                                       <groupId>com.example</groupId>
                                                       <artifactId>demo1</artifactId>
                                                       <version>0.0.1-SNAPSHOT</version>
                                                </path>
                                                <path>
```
Then you'll get:
```
 error: SubtypingChecker: qualifier interface com.example.demo.qual.Address was specified via -Aquals but its super-qualifier interface org.checkerframework.common.subtyping.qual.Unqualified was not
```

Which is fixed by adding:
`<arg>-AqualDirs=../module1/target/classes</arg>`.

Then you'll see:
```
 error: Multiple bottoms found for qualifier Address. Bottoms: Email and Address.
```
At which point you need to add a bottom qualifier that is a subytpe of both Email and Address.

**Closed** 2023-05-18 15:59 UTC

**Comment by siudeks** [comment] 2023-05-18 20:16
@smillst Thank you a lot for instructions, Is (almost) working

I am at the stage
```
error: SubtypingChecker: qualifier interface com.example.demo.qual.Address was specified via -Aquals but its super-qualifier interface org.checkerframework.common.subtyping.qual.Unqualified was not
```

And the next suggested step 
```
<arg>-AqualDirs=../module1/target/classes</arg>
```
doesn't seem to fix the issue, as that arg it has been already applied in previous steps.

My current pom config looks like:
```xml
<plugin>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.10.1</version>
	<configuration>
		<fork>true</fork> <!-- Must fork or else JVM arguments are ignored. -->
		<compilerArguments>
			<Xmaxerrs>10000</Xmaxerrs>
			<Xmaxwarns>10000</Xmaxwarns>
		</compilerArguments>
		<annotationProcessorPaths>
			<path>
				<groupId>org.checkerframework</groupId>
				<artifactId>checker</artifactId>
				<version>3.34.0</version>
			</path>
			<path>
				<groupId>com.example</groupId>
				<artifactId>demo1</artifactId>
				<version>0.0.1-SNAPSHOT</version>
			</path>
		</annotationProcessorPaths>
		<annotationProcessors>
			<annotationProcessor>org.checkerframework.common.subtyping.SubtypingChecker</annotationProcessor>
		</annotationProcessors>
		<compilerArgs>
			<!-- <arg>-Awarns</arg> --> <!-- -Awarns turns type-checking errors into warnings. -->
			<arg>-AqualDirs=../module1/target/classes</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
			<arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
			<arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
		</compilerArgs>
	</configuration>
</plugin>
```

**Comment by smillst** [comment] 2023-05-19 15:25
Yes that's simplest configuration.
