### ISSUE TITLE
NullPointerException while trying to pass a class variable inside lambda

### ISSUE THREAD

**Issue by ilmoeuro** [typetools/checker-framework#496] opened 2015-10-20 12:13 UTC
Ran CF with instructions from issue #445 but the compiler threw a NullPointerException when compiling. I couldn't get a stack trace (-AprintErrorStack didn't show enough lines with mvn -e -X) but the error is following:

    error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing /home/ilmoeuro/Asiakirjat/Projektit/membertrack/membertrack/src/main/java/fi/ilmoeuro/membertrack/data/CheckerFrameworkNPETest.java; invoke the compiler with -AprintErrorStack to see the stack trace.

Here's a minimal example that invokes the error:

```java
package fi.ilmoeuro.membertrack.data;

import java.util.Optional;

public class CheckerFrameworkNPETest {

    public static class Entity<T> {
        public final T value;
        public final Class<T> cls;

        public Entity(T value, Class<T> cls) {
            this.value = value;
            this.cls = cls;
        }
    }

    public static <T> Optional<Entity<T>> testCase(
        Class<T> targetClass
    ) {
        return Optional.<T>empty().map((T val) -> new Entity<T>(val, targetClass));
    }
}
```

The Checker Framework version is 1.9.6. I'm also using Project Lombok, but it shouldn't affect the example because it has no Lombok annotations. Other code compiles fine, this is the only file that errored.

**Comment by mernst** [comment] 2015-10-20 13:32
Thanks for the bug report.  I have confirmed it.  I believe that this is unrelated to issue #445 which you mentioned at the beginning of your report and which is about Maven.  I reproduced the error without the use of Maven by running the following command line:

$CHECKERFRAMEWORK/checker/bin/javac -processor nullness -AprintErrorStack CheckerFrameworkNPETest.java

I suspect that this is a duplicate of #448, which is a NPE in GenericAnnotatedTypeFactory just as this issue is.  However, the stack traces are slightly different, so I am not yet marking this as a duplicate.  However, I propose that we not work on this issue until issue #448 is resolved; then, once #448 is resolved, we can revisit this one.

**Closed** 2015-12-30 21:59 UTC
Labels: bug
