### ISSUE TITLE
Error produced, type checking for an extra long command in windows

### ISSUE THREAD

**Issue by ashishrana160796** [typetools/checker-framework#2074] opened 2018-07-19 11:50 UTC
Command used in windows, `java -jar ".../dist/checker.jar" -cp lib/* -processor nullness MyFile.java` with effective command length producing error coming out to be 34,000+ characters like,
`C:\Program Files\Java\jre1.8.0_171\bin\java.exe -classpath C:\checker-framework-2.5.3\checker-framework-2.5.3\checker\dist\javac.jar -ea -ea:com.sun.tools... com.sun.tools.javac.Main -Xbootclasspath/p:C:\checker-framework-2.5.3\checker-framework-2.5.3\checker\dist\jdk8.jar -classpath C:\checker-framework-2.5.3\checker-framework-2.5.3\checker\dist\checker-qual.jar;C:\......(other jars) -processor org.checkerframework.checker.nullness.NullnessChecker MyFile.java` produced file length too long error. 
Error Message 
```
at org.checkerframework.framework.util.ExecUtil.execute(ExecUtil.java:40)
        at org.checkerframework.framework.util.CheckerMain.invokeCompiler(CheckerMain.java:433)
        at org.checkerframework.framework.util.CheckerMain.main(CheckerMain.java:58)
Caused by: java.io.IOException: Cannot run program "C:\Program Files\Java\jre1.8.0_171\bin\java.exe": CreateProcess error=206, The filename or extension is too long
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at org.checkerframework.framework.util.ExecUtil.execute(ExecUtil.java:19)
        ... 2 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 6 more
```
But for same jar imports in classpath `javac -cp lib/* MyFile.java` it got compiled file w/o too long command error. This javac is the normal java w/o checker framework. Windows CP limit is exceeded with checker but not with regular `javac` command.

**Comment by mernst** [comment] 2018-07-31 18:30
Can you give a concrete, reproducible test case?  That will enable us to debug the problem and verify the fix.

**Comment by ashishrana160796** [comment] 2018-07-31 20:46
Context: I tried creating a generic command for a script which will be type-checking all JPOs of an application involving imports from 490 jars(_quite unreasonable, but generic command was required_). For comparison with other static analysis tools when scaled to large enterprise applications. 

Steps Followed: checker.jar from latest version used in above command(_1_), lib folder containing 490(_average name length of a jar, 20 chars_) approx. jars(_2_), All JPOs to be type-checked(_3_) added in command. For reproducing, these steps will raise the above issue.

Project details can't be discussed. But, I'll try to reproduce this issue with random jars & java files giving a generic test-case to reproduce in future thread.
 
Thanks!

**Comment by mernst** [comment] 2018-08-01 15:10
> Project details can't be discussed. But, I'll try to reproduce this issue with random jars & java files giving a generic test-case to reproduce in future thread.

I see.  Thanks in advance for doing this.

**Comment by mernst** [comment] 2018-08-21 18:20
I'm closing this because we didn't receive a reproducible test case.
If someone can provide a reproducible test case, we can re-open the issue.

**Closed by mernst** 2018-08-21 18:20 UTC
Labels: Unreproducible
