### ISSUE TITLE
Wildcard bounds are not inferred from types read from bytecode

### ISSUE THREAD

**Issue by gdhuse** [typetools/checker-framework#458] opened 2015-08-03 21:09 UTC
Hello,

When typechecking use of a type read from bytecode including a field declared with wildcard, the bounds of the wildcard are not inferred.  This works when checking against the source of the same file.

**Java version:**
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**OS:** OS X 10.10.4

**Test case:** https://gist.github.com/gdhuse/8068804c61d9fd231ada
*This class is read from bytecode by the checker*
```
import java.util.Set;

public class ExternalGeneric<E extends Exception>
{
   // This does not typecheck
   static final Set<ExternalGeneric<?>> staticSet = null;

   // This typechecks
   //static final Set<ExternalGeneric<? extends Exception>> staticSet = null;
}
```
*This class is typechecked*
```
public class TestWildcardFromBytecode
{
   @SuppressWarnings("unused")
   public void f()
   {
      for (final ExternalGeneric<?> element : ExternalGeneric.staticSet)
      {

      }
   }
}
```

**Expected output:** File should validate successfully

**Actual output:**
*Note: I use the ValueChecker in this example, but this issue appears with my own custom checker and some other built-in checkers*
```
> javac ExternalGeneric.java
> javac -cp checker-1.9.3.jar:. -processor org.checkerframework.common.value.ValueChecker -version  -AprintErrorStack TestWildcardFromBytecode.java

javac 1.8.0_51
warning: unknown enum constant Kind.NULL_LITERAL
  reason: class file for com.sun.source.tree.Tree not found
TestWildcardFromBytecode.java:7: error: [enhancedfor.type.incompatible] incompatible types in enhanced for loop.
      for (final ExternalGeneric<?> element : ExternalGeneric.staticSet)
                                                             ^
  found   : @UnknownVal ExternalGeneric<? extends @UnknownVal Object>
  required: @UnknownVal ExternalGeneric<? extends @UnknownVal Exception>
1 error
1 warning
```

Best regards,
 Greg

**Comment by gdhuse** [comment] 2015-08-03 21:49
Here is another instance of what I think is the same issue.  In this example, overriding a method taking an argument that is wildcard parameterized cannot be overridden.  As above, the superclass/interface must be read from bytecode for typechecking to fail.  This scenario is fairly common when dealing with 3rd party libraries.

**Test case:** https://gist.github.com/gdhuse/0c1213b0b65530444372
*These two classes must be compiled and loaded from bytecode by the checker*
```
public class ExternalGeneric<T extends Comparable<T>>
{}

interface Iface
{
   void foo(ExternalGeneric<?> arg);
}
```
*This file is typechecked*
```
public class TestOverrideWildcard implements Iface
{
   @Override
   public void foo(ExternalGeneric<?> arg)
   {}
}
```

**Expected output:** File should validate successfully

**Actual output:**
```
> javac ExternalGeneric.java
> javac Iface.java
> javac -cp checker-1.9.3.jar:. -processor org.checkerframework.common.value.ValueChecker -version  -AprintErrorStack TestOverrideWildcard.java

javac 1.8.0_51
warning: unknown enum constant Kind.NULL_LITERAL
  reason: class file for com.sun.source.tree.Tree not found
TestOverrideWildcard.java:4: error: [override.param.invalid] void foo(@UnknownVal TestOverrideWildcard this, @UnknownVal ExternalGeneric<? extends @UnknownVal Comparable<capture#759 of ? extends @UnknownVal Comparable<capture#759 of ? extends @UnknownVal Comparable<capture#759 of ?>>>> p0) in TestOverrideWildcard cannot override void foo(@UnknownVal Iface this, @UnknownVal ExternalGeneric<? extends @UnknownVal Object> p0) in Iface; attempting to use an incompatible parameter type
   public void foo(ExternalGeneric<?> arg)
                                      ^
  found   : @UnknownVal ExternalGeneric<? extends @UnknownVal Comparable<capture#759 of ? extends @UnknownVal Comparable<capture#759 of ? extends @UnknownVal Comparable<capture#759 of ?>>>>
  required: @UnknownVal ExternalGeneric<? extends @UnknownVal Object>
1 error
1 warning
```

**Comment by smillst** [comment] 2016-02-17 17:26
Issue #511 is a duplicate of this issue.  Commit 2344237 fix this issue.

**Closed by smillst** 2016-02-17 17:26 UTC
Labels: bug
