### ISSUE TITLE
Cannot infer combination of Optional.fromNullable() and or()

### ISSUE THREAD

**Issue by henrikssn** [typetools/checker-framework#596] opened 2016-02-12 15:23 UTC
private static String getOrEmpty(AtomicReference<String> ref) {
      return Optional.fromNullable(ref.get()).or("");
    }

Error:

    incompatible types in assignment.
      return fromNullable(ref.get()).or("");
                                       ^   
    found   : @NonNull ? extends T extends @Initialized @Nullable Object
    required: @Initialized @NonNull String

**Comment by mernst** [comment] 2016-02-18 08:04
Thanks for reporting the problem, and I'm sorry you are having trouble.

I cannot reproduce the problem.  The given source code is not complete (it's just a snippet rather than a complete .java file), and the given error message cites a source code line that does not appear in the snippet.  There is no fromNullable method in the JDK's Optional class, so I guess that is the Guava version.  There is no command line given that was used for compilation.

I tried the following test case (which is also checked into the repository), but type-checking of it succeeded with the command `$CHECKERFRAMEWORK/checker/bin/javac -processor nullness Issue596.java`:

    // Test case for Issue 596:
    // https://github.com/typetools/checker-framework/issues/596
    // @below-java8-jdk-skip-test

    import java.util.concurrent.atomic.AtomicReference;
    import org.checkerframework.checker.nullness.qual.*;

    class Issue596 {

      private static String getOrEmpty(AtomicReference<String> ref) {
        return Optional.fromNullable(ref.get()).or("");
      }

    }

    // From Google Guava
    class Optional<T> {

      public static <T> Optional<T> fromNullable(/*@Nullable*/ T nullableReference) {
        return new Optional<T>();
      }

      public T or(T defaultValue) {
        return defaultValue;
      }

    }

Can you please give a complete, reproducible test case so that we can understand and fix your problem?  Thanks!

**Comment by mernst** [comment] 2016-02-24 22:35
Not having heard back from the original poster, I'm going to close this issue.  If we receive a reproducible test case, then we'll re-open it.

**Closed by mernst** 2016-02-24 22:35 UTC
