### ISSUE TITLE
[Android] - Dex: Error converting bytecode to dex: Cause: Dex cannot parse version 52 byte code.

### ISSUE THREAD

**Issue by jaredsburrows** [typetools/checker-framework#1316] opened 2017-06-04 05:47 UTC
Trying the example for Android does not work: https://checkerframework.org/manual/#android-gradle and https://github.com/typetools/checker-framework/issues/564.

## Issue:
It looks like `Opt` is using Java 8 code: https://github.com/typetools/checker-framework/blob/master/checker/src/org/checkerframework/checker/nullness/Opt.java#L4. This means for Android users targeting Java 7 cannot add this as a `compile` dependency.

## Error:
```
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
...while parsing org/checkerframework/checker/nullness/Opt.class
    PARSE ERROR:
    unsupported class file version 52.0
    ...while parsing org/checkerframework/checker/nullness/Opt.class
    
1 error; aborting
:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/Users/<>/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/2.1.12/fe3cbfa020dcd5ccb5d3247fb00bb9f73018a3f5/checker-qual-2.1.12.jar' to '/Users/<>/repo/android-gif-example/build/intermediates/pre-dexed/debug/checker-qual-2.1.12_fdffc3e770dd3be820f08e78d59b8afd90e59220.jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

## Repro:
```
1. git clone https://github.com/jaredsburrows/android-gif-example
2. apply the example code from https://checkerframework.org/manual/#android-gradle
3. gradlew assembleDebug
```

**Comment by wmdietl** [comment] 2017-06-04 06:08
Hi Jared, thanks for the report.
Just to clarify: your code is not using Opt, but its existence in checker.jar is breaking dexing?
Why does the checker.jar file need to be dexed? It is a compile-time dependency only.

**Comment by jaredsburrows** [comment] 2017-06-04 06:13
@wmdietl According to the instructions here: https://checkerframework.org/manual/#android-gradle:
```
dependencies {
    ext.checkerFrameworkVersion = '2.1.12'
    ext.jdkVersion = JavaVersion.current().isJava7() ? 'jdk7' : 'jdk8'
    checkerFrameworkAnnotatedJDK "org.checkerframework:${jdkVersion}:${checkerFrameworkVersion}"
    checkerFrameworkJavac "org.checkerframework:compiler:${checkerFrameworkVersion}"
    checkerFramework "org.checkerframework:checker:${checkerFrameworkVersion}"
    compile "org.checkerframework:checker-qual:${checkerFrameworkVersion}"
}
```

This line: `compile "org.checkerframework:checker-qual:${checkerFrameworkVersion}"` contains the `Opt` class I believe. So I can't even setup a project with Android because it fails on compile time.

**Comment by jaredsburrows** [comment] 2017-06-04 06:25
I was able to figure out a hack but it only partially works: https://github.com/typetools/checker-framework/issues/1062#issuecomment-306021336

**Comment by wmdietl** [comment] 2017-06-04 06:52
Can I close this in favor of #1062? There's no point to split this discussion over two issues.

**Comment by jaredsburrows** [comment] 2017-06-04 06:53
@wmdietl Alright. After playing around with this many times, here is what I have found:
1. The example from https://checkerframework.org/manual/#android-gradle works with the Checker Framework version `1.x.x`1.9.12(version in https://github.com/typetools/checker-framework/issues/564#issuecomment-200927221 example) but not in the latest version `2.1.11`.
https://github.com/typetools/checker-framework/issues/564#issuecomment-306022169

2. Removing `options.forkOptions.jvmArgs += ["-Xbootclasspath/p:${configurations.checkerFrameworkJavac.asPath}"]` fixes this error: https://github.com/typetools/checker-framework/issues/564#issuecomment-306022014, Issue: https://github.com/typetools/checker-framework/issues/1062

**Comment by jaredsburrows** [comment] 2017-06-04 06:54
@wmdietl I believe that other issue is different and is not the dex issue.

**Comment by smillst** [comment] 2017-06-13 21:52
Android Studio 3.0 (and Android Gradle Plugin 3.0.0) [supports type annotations](https://developer.android.com/studio/preview/features/java8-support.html). I've [added new instructions](https://github.com/typetools/checker-framework/blob/master/docs/manual/external-tools.tex#L563) on how to configure Android with the Checker Framework using these new versions.  I would appreciate any feedback you have.

**Comment by mernst** [comment] 2017-07-05 19:17
I'm closing this issue because we added new instructions to resolve the problem and no one has remarked that they are not adequate.

**Closed by mernst** 2017-07-05 19:17 UTC
Labels: Android

**Comment by jaredsburrows** [comment] 2017-07-05 21:22
@mernst I'll try with my plugin again soon.

**Comment by Defuera** [comment] 2017-10-17 12:00
I tried `./gradlew clean build`, Invalidating studio cache, restarting machine. But what solved the issue is **turning Instant run off**
