### ISSUE TITLE
A bug in ImplicitsTreeAnnotator.visitLiteral

### ISSUE THREAD

**Issue by ghost** [typetools/checker-framework#2060] opened 2018-06-30 11:36 UTC
The method `ImplicitsTreeAnnotator.visitLiteral` assignes annotations to String literals based on the `stringPatterns` field of type annotations. It does so by:

1. separating the annotations in qualifier hierarchy based on whether the given string literal matches the `stringPatterns` or not

2. and then finding the greatest lower bound of all the annotations that match the string literal.

This approach can fail in case of heavily interlinked hierarchies like the one of signature checker

I encountered the bug while using this fork of signature checker: https://github.com/gsaga/checker-framework

The type hierarchy of this modified signature checker is: https://drive.google.com/open?id=1C4oxBXTABJjXy3R049FueHy2Ft2Wnv68

The error I got was:

    error: Bug in @ImplicitFor(stringpatterns=...) in type hiermachiney definition: inferred type for "[Z" is [@org.checkerframework.checker.signature.qual.SignatureBottom] which is a subtype of [@org.
    checkerframework.checker.signature.qual.BinaryNameInUnnamedPackage] but its pattern does not match the string.  matches = [[@org.checkerframework.checker.signature.qual.ClassGetName], [@org.chec
    kerframework.checker.signature.qual.InternalForm], [@org.checkerframework.checker.signature.qual.FieldDescriptorForArrayInUnnamedPackage], [@org.checkerframework.checker.signature.qual.FieldDesc
    riptorForArray], [@org.checkerframework.checker.signature.qual.FieldDescriptor]]; nonMatches = [[@org.checkerframework.checker.signature.qual.BinaryNameInUnnamedPackage], [@org.checkerframework.
    checker.signature.qual.IdentifierOrArray], [@org.checkerframework.checker.signature.qual.BinaryNameForNonArray], [@org.checkerframework.checker.signature.qual.InternalFormForNonArray], [@org.che
    ckerframework.checker.signature.qual.ClassGetSimpleName], [@org.checkerframework.checker.signature.qual.BinaryNameForNonArrayInUnnamedPackage], [@org.checkerframework.checker.signature.qual.Full
    yQualifiedName], [@org.checkerframework.checker.signature.qual.Identifier], [@org.checkerframework.checker.signature.qual.BinaryName]]; The Checker Framework crashed.  Please report the crash.
    To see the full stack trace invoke the compiler with -AprintErrorStack

As you can see the annotations whose `stringPatterns` match the literal `[Z` are:
`ClassGetName`, `InternalForm`, `FieldDescriptor`, `FieldDescriptorForArray` and `FieldDescriptorForArrayInUnnamedPackage`, and their greatest lower bound should be `FieldDescriptorForArrayInUnnamedPackage` as can be seen clearly from the hierarchy graph. But the `visitLiteral` method deduces it to be `SignatureBottom`. The reason being that the method calculates greatest lower bound of a set of types by taking two at a time.

I'm unable to reproduce this bug. As can be seen the checker framework encountered this problem while trying to infer the implicit type for `[Z`, but this error disappeared on rerunning the gradle build of the project on which I encountered this error. Trying to type check a class with the above string as a field also finished without incident:

    class Cl {
        String s = "[Z";
    }

The output of [this](https://github.com/gsaga/checker-framework/blob/6bff2f1add787243cee32a66396a53357c62e446/framework/src/main/java/org/checkerframework/framework/type/treeannotator/ImplicitsTreeAnnotator.java#L236) debugging code during the above error is:

    -----------[Z------------
    sam->	[@org.checkerframework.checker.signature.qual.ClassGetName]
    res->	[@org.checkerframework.checker.signature.qual.ClassGetName]
    sam->	[@org.checkerframework.checker.signature.qual.InternalForm]
    res->	[@org.checkerframework.checker.signature.qual.BinaryNameForNonArrayInUnnamedPackage]
    sam->	[@org.checkerframework.checker.signature.qual.FieldDescriptorForArrayInUnnamedPackage]
    res->	[@org.checkerframework.checker.signature.qual.SignatureBottom]
    sam->	[@org.checkerframework.checker.signature.qual.FieldDescriptorForArray]
    res->	[@org.checkerframework.checker.signature.qual.SignatureBottom]
    sam->	[@org.checkerframework.checker.signature.qual.FieldDescriptor]
    res->	[@org.checkerframework.checker.signature.qual.SignatureBottom]
    checker failed on this string

This is the procedure `visitLiteral` followed:

1. Find the greatest lower bound of `ClassGetName` and `InternalForm`: `BinaryNameForNonArrayInUnnamedPackage`

2. Find the greatest lower bound of `BinaryNameForNonArrayInUnnamedPackage` and `FieldDescriptorForArrayInUnnamedPackage`: `SignatureBottom`

A better approach could be to find the intersection of the sets of all the subtypes of matching annotations and then return the type highest among them.

**Comment by mernst** [comment] 2018-08-06 03:47
Thanks for bringing this up.

1. There is something odd about your pasted output.  It starts
```error: Bug in @ImplicitFor(stringpatterns=...) in type hiermachiney definition```
but "type hiermachiney" should be "type hierarchy".  Did you make some edits rather than pasting verbatim?

2. Can you clarify "I'm unable to reproduce this bug."?
Does that mean that you saw it once but you never saw it again, even when you ran the same command?
Or that you can reproduce it in an end-to-end test case but not in an isolated test case?

Please do try to reproduce it.  Otherwise it's difficult to understand, reproduce, fix, and verify.
A unit test is most convenient, but an end-to-end test is much better than nothing.  An end-to-end test might look like

```
git clone https://github.com/gsaga/checker-framework
cd checker-framework
./gradlew build
javac -processor MyProcessor MyFile.java
```

(though I realize the above is not complete).

Thanks!

3. Thanks for attaching the PDF graph of the hierarchy; that makes the hierarchy, and your bug report, easier to understand.
It's a bit confusing that the type hierarchy is upside down (with subclasses *above* superclasses).  In the future, can you turn it right side up?

4.

> Find the greatest lower bound of ClassGetName and InternalForm: BinaryNameForNonArrayInUnnamedPackage

This could be considered a bug in qualHierarchy.greatestLowerBounds.
There is no glb of those two types, so perhaps the method should have thrown an exception rather than returning a lower bound that is not the greatest lower bound.
I am testing a change that will make the method crash instead of returning a misleading result.

5.

> A better approach could be to find the intersection of the sets of all the subtypes of matching annotations and then return the type highest among them.

Unfortunately, there is not guaranteed to be a highest type among them.
Suppose that the full set of arguments to glb is: {ClassGetName, InternalForm}.
Their lower bounds (the intersection you mentioned above) is

BinaryNameForNonArrayInUnnamedPackage
Identifier
FieldDescriptorForArrayInUnnamedPackage
SignatureBottom

but there is no greatest among these.  BinaryNameForNonArrayInUnnamedPackage and FieldDescriptorForArrayInUnnamedPackage are incomparable: neither is greater than the other.

If the type hierarchy is a *lattice* (as required by [section 30.4.7 of the manual](https://checkerframework.org/manual/#creating-bottom-and-top-qualifier)), then every set of points has a unique least upper bound and greatest lower bound.  For a lattice, your algorithm works -- but if the type hierarchy is a lattice, then the current algorithm also works and is guaranteed to give the same result.

The error that you received was `Bug in @ImplicitFor(stringpatterns=...) in type hierarchy definition`.  There are a couple different root causes that can lead to this.  One of them is a type hierarchy that is not a lattice, and that is the cause in your case.  I'm sorry that this error message was rather obscure!  As I noted above, I'm currently testing some changes to make the root cause more explicit.  In the meanwhile, could you please enrich your type hierarchy (add types) so that it is a lattice with unique lubs and glbs?

**Comment by gsaga** [comment] 2018-08-06 16:03
1. The typo was because of a script I have which `codifies` the clipboard content to be posted as markdown. It also replaces my username with `user` and my local machine name (i.e. `arch`) with `machine`. It needs to have `arch` surrounded with word boundaries in the regex.

2. The error appears seemingly randomly. It disappears on repeating the build steps and doesn't pop up if the offending part is pulled out as a test case. That's why I added the debugging code to `ImplicitTreeAnnotator.java` and created this issue when the error appeared again.

>In the meanwhile, could you please enrich your type hierarchy (add types) so that it is a lattice with unique lubs and glbs?

Ok. I'll get on it.

**Comment by mernst** [comment] 2018-08-06 16:26
Thanks for the explanations -- and for filing the bug in the first place.
Thanks in advance for fixing your type hierarchy.

**Comment by mernst** [comment] 2019-04-12 02:33
I'm closing this for now because there has been no discussion about the results after my suggestions.
We can re-open it if the problem persists and there is new information.

**Closed by mernst** 2019-04-12 02:33 UTC
