### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jindalshiva** [typetools/checker-framework#3102] opened 2020-02-22 12:51 UTC
##I am combining checker framework with my android studio but I am facing a build error, when I run gradlew assembleCheckTypes 
from terminal of android studio.

##As a android app developer,
##I need establish checker framework with android studio,
##so that I can use checker framework facility with android studio.

![Error](https://user-images.githubusercontent.com/33796163/75092670-290bf800-55a0-11ea-82fd-fe17c692ab05.PNG)

**Comment by mernst** [comment] 2020-02-22 14:12
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/typetools/checker-framework/issues/new) and the [https://checkerframework.org/manual/#reporting-bugs](bug reporting section of the manual)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

Also, please confirm whether the command works outside your IDE.  If so, the problem is in your IDE setup.

**Comment by mernst** [comment] 2020-03-02 17:38
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2020-03-02 17:38 UTC
Labels: Unreproducible
