### ISSUE TITLE
Type argument inference crash on interdependent methods 

### ISSUE THREAD

**Issue by twistedsquare** [typetools/checker-framework#953] opened 2016-10-21 21:01 UTC
Here is a fairly simple program (cut down from my real code) with a line of stream-processing code:

```
import java.util.*;
import java.util.stream.Collectors;

class CheckerTest
{
    public static void test()
    {
        List<String> initial = new ArrayList<>();
        List<Integer> counts = initial.stream().skip(1).map(l -> count("", l)).collect(Collectors.toList());
    }
    private static int count(String s, String l)
    {
        return 0;
    }
}
```

When I try to compile that using `javac -processor NullnessChecker CheckerTest.java` (version 2.1.4) I get these errors:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: Object
  superType: Integer; invoke the compiler with -AprintErrorStack to see the stack trace.
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @Nullable Object
  superType: Integer; invoke the compiler with -AprintErrorStack to see the stack trace.
2 errors
```

I don't think there should be any errors: it's perfectly valid Java code which javac compiles fine when not running the annotation processor.

**Comment by twistedsquare** [comment] 2016-10-21 21:17
This may or may not be the same bug; it gives the same type of error:

```
import java.util.*;
import java.util.function.Function;
import org.checkerframework.checker.nullness.qual.NonNull;

class CheckerTest2
{
    private static List<List<?>> strs = new ArrayList();

    public static <R,T> List<@NonNull R> mapList(List<@NonNull T> list, Function<@NonNull T, @NonNull R> func)
    {
        ArrayList<@NonNull R> r = new ArrayList<>(list.size());
        for (T t : list)
            r.add(func.apply(t));
        return r;
    }

    public static List<String> test()
    {
        return mapList(strs, s -> {return new String();});
    }
}
```

Gives:
```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Object
  superType: List<? extends Object>; invoke the compiler with -AprintErrorStack to see the stack trace.
```

**Comment by smillst** [comment] 2016-10-21 23:13
Thanks for reporting this/these issue!  I've add the testcases framework/tests/all-systems/Issue953.java and checker/tests/nullness/java8/lambda/Issue953b.java.  (Note that the first example crash with any checker and the second only crash with the Nullness Checker. I'm not sure why.)

Both of these crashes are occurring because type argument inference is failing.  You can work around both by explicitly specifying the type argument: `Collectors.<String>toList()` in the first example and `CheckerTest2..<String, List<?>>mapList(...)` in the second.

We should be able to come up with some way detect these cases and not crash.

**Comment by zenixan** [comment] 2016-11-07 18:05
Hello,

I have tried to fix issue related to interdependent method invocations.
Unfortunately this fix does not touch problem with interdependent static method invocations.
Please review commit.

**Comment by smillst** [comment] 2016-11-07 18:44
@zenixan Thanks for the contribution.  Could you please open a pull request with the change so that we can review it using our normal process.  Thanks!

**Comment by smillst** [comment] 2016-11-14 22:29
This issue is a duplicate of #531, but now the failing test case is crashing, so I'm closing that issue in favor of this one.

**Comment by smillst** [comment] 2016-12-07 23:40
The test cases submitted in this issue no longer crash.  They do issue false positives warnings because Java 8 type inference isn't implement.  This false positives should go away once #979 is fixed.  (These test cases will be added to that issue.)

**Closed by smillst** 2016-12-07 23:40 UTC
Labels: crash
