### ISSUE TITLE
Flow Expression parser: cannot parse expression referring to static field of outer class

### ISSUE THREAD

**Issue by jthaine** [typetools/checker-framework#764] opened 2016-05-31 21:20 UTC
When type checking this code with the Nullness Checker:
````
import org.checkerframework.checker.nullness.qual.*;

public class Issue764 {
    public static @Nullable Object field = null;
    static class MyClass {
        @RequiresNonNull("field")
        public static void method() { }

        public void otherMethod() {
            field = new Object();
            method();
        }
        public void otherMethod2() {
            //:: error: (contracts.precondition.not.satisfied)
            method();
        }
    }
````
Expected: `contracts.precondition.not.satisfied` on the call to `method()`
Actual:  no error

 e717441 is a possible fix for this issue, ~~but it can't be fully tested because of issue general dataflow problems with referencing a static field in an inner class (#818).~~

~~Blocked by #818~~
Revert part of this comment that suppresses a warning related to this issue: https://github.com/codespecs/daikon/commit/437ca4a30c8fd8fa2489e26ae38253117640ad1c

**Comment by mernst** [comment] 2016-06-02 03:04
I added a test case in file `checker-framework/checker/tests/nullness/Issue764.java`, but I cannot reproduce the parse failure.  Compilation did not produce any warnings or errors, though, and that is a bug.

**Comment by jthaine** [comment] 2016-06-02 19:08
Thanks for adding the test case. The failure reproduces in branch issue657 (I updated the description above to mention that).

**Comment by jthaine** [comment] 2016-06-14 18:18
**Important**: this is only closed in branch issue657.

**Comment by smillst** [comment] 2016-06-28 20:02
I've improved the test case so that it fails on master. (checker/tests/nullness/Issue764.java)  Since this issue it not yet fixed on master, I'm re-opening it.

**Comment by smillst** [comment] 2016-06-28 20:27
See e717441 from a possible fix for this issue

**Closed** 2016-09-13 21:37 UTC
Labels: JavaExpressions
