### ISSUE TITLE
Help with packaging checker for Maven Central

### ISSUE THREAD

**Issue by seanmcl** [typetools/checker-framework#2326] opened 2019-02-24 17:21 UTC
We've recently pushed the [KMS compliance checker](https://github.com/awslabs/aws-kms-compliance-checker), referenced in the CF manual, [to Maven Central](https://search.maven.org/search?q=a:aws-kms-compliance-checker).  Adding a dependency (example [here](https://github.com/seanmcl/kms-compliance-example)) enables CF to find the checker, but not the stub file.  The file is included in the top level of the JAR file.  I didn't see any instructions in the CF manual about how to distribute or refer to a stub file in a JAR file.  Could someone on the CF team offer advice on how to tell CF to find it?

```
~/Dropbox/sean/src/third_party/aws-kms-example ‹master›  [2019-02-24 12:15:42]
[0]$ gradle clean build

> Task :compileJava
Note: Did not find stub file or files within directory: GenerateDataKeyRequest.astub /Users/seanmcl/Dropbox/sean/src/third_party/aws-kms-example/GenerateDataKeyRequest.astub GenerateDataKeyRequest.astub

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
```

Thanks!

**Comment by mernst** [comment] 2019-02-24 19:55
I cannot reproduce your problem.
What is the `aws-kms-example` directory?

I tried using `git@github.com:seanmcl/kms-compliance-example.git` for that, but that led to a build failure.  (I am using JDK 8, and I suspect that is the problem.)

I ran these commands:

```
cd ~/tmp
git clone git@github.com:seanmcl/kms-compliance-example.git
cd kms-compliance-example
gradle build
```

And the output of the last one was:

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.4.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Can you give a few more details to enable me to reproduce the problem?
I have a hypothesis about how to fix it, but I need to reproduce the problem in order to test the fix.

**Comment by seanmcl** [comment] 2019-02-25 01:30
Sorry, that's frustrating.  I just tried again:

```
~  [2019-02-24 20:21:59]
[0]$ cd ~/tmp
~/tmp  [2019-02-24 20:25:46]
[0]$ git clone https://github.com/seanmcl/kms-compliance-example.git
Cloning into 'kms-compliance-example'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 49 (delta 15), reused 47 (delta 13), pack-reused 0
Unpacking objects: 100% (49/49), done.
~/tmp  [2019-02-24 20:28:28]
[0]$ cd kms-compliance-example
~/tmp/kms-compliance-example ‹master›  [2019-02-24 20:28:30]
[0]$ gradle build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
Note: Did not find stub file or files within directory: GenerateDataKeyRequest.astub /Users/seanmcl/tmp/kms-compliance-example/GenerateDataKeyRequest.astub GenerateDataKeyRequest.astub

BUILD SUCCESSFUL in 7s
2 actionable tasks: 2 executed
~/tmp/kms-compliance-example ‹master›  [2019-02-24 20:28:41]
[0]$
```

I wonder if it's a gradle version issue.  I'll add a gradlew file and see if that fixes your problem.

**Comment by seanmcl** [comment] 2019-02-25 01:36
Added gradle wrapper.  Please try 

```
$ cd ~/tmp
$ rm -rf kms-compliance-example && git clone git@github.com:seanmcl/kms-compliance-example.git
$ cd kms-compliance-example
$ ./gradlew build
```

If this doesn't work I'm not sure what to do.  I'm not a Java programmer.

**Comment by seanmcl** [comment] 2019-02-25 01:38
Here is the JAR file contents on Maven Central:

```
$ jar -tf /Users/seanmcl/.gradle/caches/modules-2/files-2.1/software.amazon.checkerframework/aws-kms-compliance-checker/1.0.1/5dad3943f214a190f260ebe597548612cbd80b7e/aws-kms-compliance-checker-1.0.1.jar
META-INF/
META-INF/MANIFEST.MF
com/
com/amazon/
com/amazon/checkerframework/
com/amazon/checkerframework/compliance/
com/amazon/checkerframework/compliance/kms/
com/amazon/checkerframework/compliance/kms/ComplianceAnnotatedTypeFactory.class
com/amazon/checkerframework/compliance/kms/ComplianceChecker.class
com/amazon/checkerframework/compliance/kms/ComplianceVisitor.class
com/amazon/checkerframework/compliance/kms/ComplianceAnnotatedTypeFactory$ComplianceTreeAnnotator.class
LICENSE
GenerateDataKeyRequest.astub
```

Is it possible to package the stubs with the jar?  Do the stub files need to be in `resources`, `stubs` or some other directory?

**Comment by mernst** [comment] 2019-02-25 17:45
I can now reproduce the problem.  Thanks!

**Comment by mernst** [comment] 2019-02-26 22:35
The problem is where you placed the `.astub` file within the `.jar` file.
[Section "Using a stub file" in the manual](https://checkerframework.org/manual/#stub-using) says:
> The checker author should place jdk.astub in the same directory as the Checker class, i.e., the subclass of BaseTypeVisitor.

You put `GenerateDataKeyRequest.astub` at the top level in `aws-kms-compliance-checker-1.0.1.jar`.
In a `.jar` file that contains more than one checker, putting `.astub` files at the top level would be error-prone and confusing.
Could you try putting `GenerateDataKeyRequest.astub` as a sibling of `ComplianceChecker.class` in the `.jar` file?

I will add a diagnostic to warn about this problem.

**Comment by seanmcl** [comment] 2019-02-27 00:52
I moved the stubs to the spot you mention, but it still doesn't work.  It's not in maven search yet, but it's in the repo:

```
$ curl --output /tmp/foo.jar https://search.maven.org/remotecontent\?filepath\=software/amazon/checkerframework/aws-kms-compliance-checker/1.0.2/aws-kms-compliance-checker-1.0.2.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9031  100  9031    0     0  33462      0 --:--:-- --:--:-- --:--:-- 33572
~/Dropbox/sean/src/third_party/aws-kms-example ‹master*›  [2019-02-26 19:49:56]
[0]$ jar -tf /tmp/foo.jar
META-INF/
META-INF/MANIFEST.MF
com/
com/amazon/
com/amazon/checkerframework/
com/amazon/checkerframework/compliance/
com/amazon/checkerframework/compliance/kms/
com/amazon/checkerframework/compliance/kms/ComplianceAnnotatedTypeFactory.class
com/amazon/checkerframework/compliance/kms/ComplianceChecker.class
com/amazon/checkerframework/compliance/kms/ComplianceVisitor.class
com/amazon/checkerframework/compliance/kms/ComplianceAnnotatedTypeFactory$ComplianceTreeAnnotator.class
com/amazon/checkerframework/compliance/kms/GenerateDataKeyRequest.astub
LICENSE
```

```
$ gradle build

> Task :compileJava
Note: Did not find stub file or files within directory: GenerateDataKeyRequest.astub /Users/seanmcl/Dropbox/sean/src/third_party/aws-kms-example/GenerateDataKeyRequest.astub GenerateDataKeyRequest.astub
Note: Did not find stub file or files within directory: aws-kms-compliance-checker.jar /Users/seanmcl/Dropbox/sean/src/third_party/aws-kms-example/aws-kms-compliance-checker.jar aws-kms-compliance-checker.jar

BUILD SUCCESSFUL in 1s
```

**Comment by mernst** [comment] 2019-02-27 16:13
I'm sorry you are still having trouble.

It looks to me like maybe there is a problem in the Maven Central configuration for `ams-kms-compliance-checker`.

Here is how I came to that hypothesis.

1. [Build the Checker Framework](https://checkerframework.org/manual/#build-source) from its version control repository.
Include at least up to commit ac8c26be792f7178de8c2a949c44f6953ed7224f; if you do `git pull` in the `checker-framework` repository, this will happen.

2. Run the following commands:

```
cd ~/tmp
rm -rf kms-compliance-example && git clone git@github.com:seanmcl/kms-compliance-example.git kms-compliance-example
cd ~/tmp/kms-compliance-example
./gradlew build -PcfLocal
```

The output I obtain includes

```
warning: GenerateDataKeyRequest.astub should be in the same directory as the checker class, but it at the top level of a jar file: jar:file:/home/mernst/.gradle/caches/modules-2/files-2.1/software.amazon.checkerframework/aws-kms-compliance-checker/1.0.1/5dad3943f214a190f260ebe597548612cbd80b7e/aws-kms-compliance-checker-1.0.1.jar!/GenerateDataKeyRequest.astub
```

It's weird that this references `aws-kms-compliance-checker/1.0.1` even though [build.gradle](https://github.com/seanmcl/kms-compliance-example/blob/master/build.gradle#L15) contains `version: '1.0.2'`.  Is it possible that the `software.amazon.checkerframework/aws-kms-compliance-checker` artifact is misconfigured at Maven Central or elsewhere?  Its 1.0.2 jar file does look reasonable to me, but somehow it is not getting used by the `kms-compliance-example` repository.

Please let me know if you cannot reproduce the behavior I saw, or if I can do more to help debug this issue, or if you find that this version mismatch is the fault of the Checker Framework.  Thanks.

**Comment by mernst** [comment] 2019-02-27 17:26
Found it.  The problem is that [this commit](https://github.com/seanmcl/kms-compliance-example/commit/027374dc9c7ff27362477645ce16708d4f242d32) failed to change [these](https://github.com/seanmcl/kms-compliance-example/blob/master/checkerframework.gradle#L14) [lines](https://github.com/seanmcl/kms-compliance-example/blob/master/checkerframework.gradle#L25).

Once I updated those, everything works and `./gradlew build` outputs 
```
> Task :compileJava FAILED
/homes/gws/mernst/tmp/kms-compliance-example/src/main/java/Kms.java:13: error: [argument.type.incompatible] incompatible types in argument.
                .withKeySpec(keySpec);
                             ^
  found   : @StringVal("AES_128") String
  required: @StringVal("AES_256") String
1 error
```

Could you try that?

**Comment by seanmcl** [comment] 2019-02-27 17:38
Wonderful! Thanks so much for digging in. I wasn’t sure how to debug.

**Comment by mernst** [comment] 2019-02-27 17:42
I'm happy to help.  Go ahead and close the issue if it is resolved to your satisfaction.  And let us know if you have any other problems or questions.

**Closed** 2019-02-27 17:47 UTC
