### ISSUE TITLE
Incompatible type error for inferred type of Function.identity()

### ISSUE THREAD

**Issue by rcchan** [typetools/checker-framework#1297] opened 2017-05-22 23:48 UTC
The following code produces no error.

```
Map<SimpleEntry, List<SimpleEntry>> x =
        Stream.of(Stream.of(new SimpleEntry<>("A", "B")))
            .flatMap(Function.<Stream<SimpleEntry<String, String>>>identity())
            .collect(Collectors.groupingBy(e -> e));
```

Removal of the `<Stream<SimpleEntry<String, String>>>` type parameter results in the following error.

> ```
> error: [argument.type.incompatible] incompatible types in argument.
>             .collect(Collectors.groupingBy(e -> e));
>                                           ^
>   found   : @Initialized @NonNull Collector<@Initialized @NonNull SimpleEntry, ? extends @Initialized @NonNull Object, @Initialized @NonNull Map<@Initialized @NonNull SimpleEntry, @Initialized @NonNull List<@Initialized @NonNull SimpleEntry>>>
>   required: @Initialized @NonNull Collector<? extends @Initialized @NonNull Object super ? extends @Initialized @NonNull Object, ? extends @Initialized @NonNull Object, @Initialized @NonNull Map<@Initialized @NonNull SimpleEntry, @Initialized @NonNull List<@Initialized @NonNull SimpleEntry>>>
> 1 error
> ```

Formatted:

> ```
> Found:
> @Initialized @NonNull Collector<
>   @Initialized @NonNull SimpleEntry,
>   ? extends @Initialized @NonNull Object,
>   @Initialized @NonNull Map<
>     @Initialized @NonNull SimpleEntry,
>     @Initialized @NonNull List<
>       @Initialized @NonNull SimpleEntry>>>
> 
> Required:
> @Initialized @NonNull Collector<
>   ? extends @Initialized @NonNull Object super ? extends @Initialized @NonNull Object,
>   ? extends @Initialized @NonNull Object,
>   @Initialized @NonNull Map<
>     @Initialized @NonNull SimpleEntry,
>     @Initialized @NonNull List<
>       @Initialized @NonNull SimpleEntry>>>
> ```

javac doesn't appear to have any issue with compiling and inferring the correct types and IntelliJ says that the explicit type parameters can be inferred.

Is this error expected?

**Comment by wmdietl** [comment] 2017-05-22 23:54
This is an unfortunate result of https://github.com/typetools/checker-framework/issues/979
This recent fix: https://github.com/typetools/checker-framework/commit/1c0dac4db1a0032af0c814e09372cdae80f2f5ad
helped in some situations. I will try whether it solved this issue.

**Comment by rcchan** [comment] 2017-05-23 01:21
Ah, I see. Thanks for the quick response.  Feel free to close as duplicate.

**Comment by wmdietl** [comment] 2017-06-01 22:45
I'm closing this as duplicate of #979, regarding the method type argument inference.
This also helped reveal another deficiency, which I filed as #1312.

**Closed by wmdietl** 2017-06-01 22:45 UTC
Labels: duplicate
