### ISSUE TITLE
Nullness Checker crash: AsSuperVisitor: type is not an erased subtype of supertype 9

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/checker-framework#1417] opened 2017-07-21 19:17 UTC
In a repo with master and #1387 take:

```java
interface Bar {}
interface SubBar extends Bar {}

interface Barber<S extends Bar> {
  S call(S s);
}

abstract class Crash12 {
  abstract void foo(Barber<?> b);

  void crash() {
    foo( (SubBar p) -> p);
  }
}
```

Running the Nullness Checker gives:

```
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Bar
  superType: @Initialized @NonNull SubBar
  Compilation unit: Crash12.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:155)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:59)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:1112)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:485)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:238)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:173)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:151)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1814)
  org.checkerframework.checker.nullness.NullnessVisitor.commonAssignmentCheck(NullnessVisitor.java:221)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitLambdaExpression(BaseTypeVisitor.java:1161)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitLambdaExpression(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1628)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2241)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:939)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:160)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
  org.checkerframework.checker.initialization.InitializationVisitor.visitBlock(InitializationVisitor.java:298)
  org.checkerframework.checker.initialization.InitializationVisitor.visitBlock(InitializationVisitor.java:58)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:568)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:382)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:58)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:262)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:160)
```

**Comment by smillst** [comment] 2017-07-21 22:38
Fixed in #1387.  The crash was caused by an incorrect underlying (Java) type in the annotated type for the lambda.

**Closed** 2017-08-02 16:58 UTC
Labels: crash
