### ISSUE TITLE
NPE in CFGBuilder$CFGTranslationPhaseOne

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1586] opened 2017-10-15 06:57 UTC
Tested with version 2.2.1:

```java
import java.util.concurrent.ExecutorService;

class T {

  void f(ExecutorService es) {
    es.execute(
        () -> {
          try {
            System.err.println();
          } catch (Throwable throwable) {
            System.err.println();
          } finally {
            es.execute(
                () -> {
                  System.err.println();
                });
          }
        });
  }
}
```

```
$ ~/jsr308/checker-framework-2.2.1/checker/bin/javac -processor Nullness T.java -AprintErrorStack
...
error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing ../T.java
  Compilation unit: ../T.java
  Exception: java.lang.NullPointerException; Stack trace: com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1554)
  org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1585)
  org.checkerframework.framework.flow.CFCFGBuilder.run(CFCFGBuilder.java:61)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1135)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1055)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1418)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:248)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:283)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:164)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:962)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:495)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:185)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
```

**Comment by wmdietl** [comment] 2017-10-15 19:40
This probably has the same root cause as #1520. I'll look whether we can add a work-around until a proper fix is found.

**Comment by smillst** [comment] 2017-10-17 18:16
Closed in favor of #1520.

**Closed by smillst** 2017-10-17 18:16 UTC
Labels: crash
