### ISSUE TITLE
initialization issue with step builder pattern

### ISSUE THREAD

**Issue by urbandroid** [typetools/checker-framework#1770] opened 2018-01-19 10:58 UTC
With this structure:

```
import org.checkerframework.checker.nullness.qual.EnsuresNonNull;
import org.checkerframework.checker.nullness.qual.MonotonicNonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

public class StepBuilder {
    public StepBuilder() {
    }

    public static NameStep newBuilder() {
        return new Steps();
    }

    public static interface NameStep {
        ServerStep name(String name);
    }

    public static interface ServerStep {

        public BuildStep onlocalhost();

        public CredentialStep onRemoteHost(String host);
    }

    public static interface CredentialStep {
        public BuildStep credentials(String user, String password);

    }

    public static interface BuildStep {
        public UserConfiguration build();
    }


    private static class Steps implements NameStep, ServerStep, CredentialStep, BuildStep {

        private @MonotonicNonNull String name;
        private @Nullable String host;
        private @Nullable String user;
        private @Nullable String password;


        @Override
        @EnsuresNonNull({"name"})
        public ServerStep name(String name) {
            if (name == null)
                throw new IllegalArgumentException("no null please");
            else
                this.name = name;
            return this;
        }

        @Override
        public BuildStep onlocalhost() {
            this.host = "localhost";
            return this;
        }

        @Override
        public CredentialStep onRemoteHost(String host) {
            this.host = host;
            return this;
        }

        @Override
        public BuildStep credentials(String user, String password) {
            this.user = user;
            this.password = password;
            return this;
        }


        @Override
        public UserConfiguration build() {
            UserConfiguration userConfiguration;
            userConfiguration = new UserConfiguration(name);
            ServerDetails serverDetails = new ServerDetails(host);
            serverDetails.setUser(user);
            serverDetails.setPassword(password);
            userConfiguration.setServerDetails(serverDetails);
            return userConfiguration;
        }
    }
}
```

```
public class UserConfiguration {
    private final String name;
    private @Nullable ServerDetails serverDetails;

    UserConfiguration(String name) {
        this.name = name;
    }

    @Nullable public ServerDetails getServerDetails() {
        return serverDetails;
    }

    public void setServerDetails(ServerDetails serverDetails) {
        this.serverDetails = serverDetails;
    }

    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return "UserConfiguration{" +
                "name='" + name + '\'' +
                ", serverDetails=" + serverDetails +
                '}';
    }
}
```
When compiled this error is shown:

Error:(88, 59) java: [argument.type.incompatible] incompatible types in argument. found : @Initialized @MonotonicNonNull String
required: @Initialized @NonNull String

for this line:

userConfiguration = new UserConfiguration(name);
But due to used pattern there is now way that when it gets to build method (which can not be called before NameStep name method) "name" field to be null.

How should i fix this? If i put another @EnsuresNonNull at build and put another null check at there it fixes but that is why we use Step builder to be sure when build called mandatory field already set and only check when it set why should we check again?

Is there a elegant way to fix it?

**Comment by mernst** [comment] 2018-01-19 12:46
You said "there is no way that when it gets to build method (which can not be called before NameStep name method) `name` field to be null."
This is on the right track.

You need to convey this fact to the Nullness Checker.  The Nullness Checker does modular verification, analyzing one method at a time.  You need to express to each step of why the code is correct.  In this case, you need to express why the `name` field cannot be null.

From your code, it seems like the class's contract requires that a client must call `name()` to set the `name` field before calling `build()`, and this might be a missing part of your proof.  (I am not positive, however, because the code is undocumented, there are parts that are extraneous to the `name` field, and you haven't full expressed your proof that `name` cannot be rull.)  You have already written an `@EnsuresNonNull` annotation on `Steps.name()`.  A `@RequiresNonNull` annotation on `Steps.build()` would enforce that clients obey that contract, and would enable the Nullness Checker to verify that `new UserConfiguration(name)` is a legal call.

The manual explains this methodology in these two sections:
https://checkerframework.org/manual/#common-problems
https://checkerframework.org/manual/#handling-warnings

I hope this helps.

PS:  I cannot reproduce your problem using the source code you provided, because the code does not compile.  (It uses undefined classes like `ServerDetails`.)
It is really helpful if you provide a compilable test case, and a minimal one that focuses in on the problem.  That permits us to try our suggestions, and saves everyone time.  Thanks!

**Comment by urbandroid** [comment] 2018-01-19 13:37
@mernst i added the `ServerDetails` to question.

 "From your code, it seems like the class's contract requires that a client must call name() to set the name field before calling build()," you are right.

When  `@RequiresNonNull("name")` added on `Steps.build()` method i get this error instead:

```
Error:(84, 34) java: [contracts.precondition.override.invalid] Precondition must be no stronger than in superclass.
  Method
    @Initialized @NonNull UserConfiguration build(@Initialized @NonNull Steps this) in 
   stepbuilder.StepBuilder.Steps
    cannot override
    @Initialized @NonNull UserConfiguration build(@Initialized @NonNull BuildStep this) in 
    stepbuilder.StepBuilder.BuildStep
  Precondition is too strong: '@NonNull' for 'this.name'
```

**Comment by urbandroid** [comment] 2018-01-19 16:32
"It is really helpful if you provide a compilable test case, and a minimal one that focuses in on the problem. That permits us to try our suggestions, and saves everyone time. Thanks!" i think 3 class is minimalistic enough .

**Comment by wmdietl** [comment] 2018-01-19 20:30
The Checker Framework implements [Behavioral Subtyping](https://en.wikipedia.org/wiki/Liskov_substitution_principle); that is, a method cannot strengthen the preconditions of a supertype. Without this restriction, a dynamically bound invocation of the method could violate a precondition of an unknown subclass.

That is, you need to provide the same, or a stronger, pre-condition on the method that `build()` is overriding.

**Comment by urbandroid** [comment] 2018-01-20 13:01
@wmdietl so in the end how can i achieve the desired behavior with checker framework? that was the main issue in the beginning. `name` method `@EnsuresNonNull` and build can not be called without calling `name` method and checker complains when `name`  field not checked again in `build` method. How to solve elegantly?

**Comment by mernst** [comment] 2018-02-13 19:41
> i added the ServerDetails to question.

I don't understand.  The code in this issue still does not contain a definition for it.

**Comment by mernst** [comment] 2018-02-19 17:21
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2018-02-19 17:21 UTC
Labels: Unreproducible

**Comment by urbandroid** [comment] 2018-02-21 21:56
@mernst sorry for delay. question updated with `ServerDetails` .

**Comment by pSub** [comment] 2018-03-29 12:44
I am having trouble dealing with builder patterns, too. The problem in your specific case is, that your builder just isn't null-safe and therefore you cannot prove it to be null-safe. A simple counter example is

    ((BuildStep) StepBuilder.newBuilder()).build().getName();

This will produce a NPE. There are ways to formulate the builder pattern in a way such that you can prove it null-safe with the checker framework. For example https://github.com/vorburger/eclipse-null-eea-augments/blob/12a59e0dad053536bb1ac1beb25a23673b24eca2/examples/eclipse/hello/src/main/java/ch/vorburger/nulls/examples/hello/Person.java should be null-safe and the prove with the checker framework should be straight forward. However this solution does not seem very elegant nor fast / lightweight. I am currently playing with similar but more lightweight approaches. However so far I haven't found a really good solution.
