### ISSUE TITLE
org.checkerframework.checker.tainting.classic.TaintingClassicChecker throws "LetExpr is not part of a public API"  error message

### ISSUE THREAD

**Issue by uladzimir-shymanski** [typetools/checker-framework#469] opened 2015-09-10 11:42 UTC
error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing C:\OTW\platform\src\otw\platform\TracksVersion.java; message: LetExpr is not part of a public API
  Compilation unit: C:\OTW\platform\src\otw\platform\TracksVersion.java
  Exception: java.lang.AssertionError: LetExpr is not part of a public API; Stack trace: com.sun.tools.javac.tree.JCTree$Let
Expr.getKind(JCTree.java:2429)
  com.sun.source.util.TreePath.<init>(TreePath.java:97)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
  com.sun.source.util.TreePath$1PathFinder.scan(TreePath.java:70)
  com.sun.source.util.TreePath$1PathFinder.scan(TreePath.java:65)
  com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  com.sun.source.util.TreePath.getPath(TreePath.java:79)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getPath(AnnotatedTypeFactory.java:2166)
  org.checkerframework.framework.util.defaults.QualifierDefaults.nearestEnclosingExceptLocal(QualifierDefaults.java:251)
  org.checkerframework.framework.util.defaults.QualifierDefaults.applyDefaults(QualifierDefaults.java:338)
  org.checkerframework.framework.util.defaults.QualifierDefaults.annotate(QualifierDefaults.java:235)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:903)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:882)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:722)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1805)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:604)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.ja
va:931)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:898)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:882)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:722)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1805)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:296)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:173)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:70)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:890)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:452)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:205)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)

**Comment by mernst** [comment] 2015-09-10 11:46
I'm sorry you are having this problem.
Could you send us the files you are compiling and also give the command line?  This will enable us to reproduce your problem and verify that it is fixed.
Here are [instructions](http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#reporting-bugs) for submitting a bug report.
Thanks!

**Comment by uladzimir-shymanski** [comment] 2015-09-11 07:59
Sorry, according to the policy of our company I cannot send you our source code that I'm trying to process..
Here are my compiler args:
compileJava {
    options.debug = true
    options.fork = true
    options.forkOptions.executable = 'c:/checker-framework-1.9.5/checker/bin/javac.bat'
    options.compilerArgs = ['-XDignore.symbol.file=true', '-version', '-implicit:class', '-Awarns', '-AprintErrorStack', '-Xmaxerrs', '10', '-processor', 'org.checkerframework.checker.tainting.classic.TaintingClassicChecker']
}
I use Gradle to build project.

I'll try to investigate the issue by myself and let you know about results.

**Comment by mernst** [comment] 2015-09-11 13:54
I understand the need to protect your employer's source code.
We don't need the original source code -- if you could minimize your test case to a small snippet that you can send to us, that would be great, and it would enable us to fix the bug for you.
Thanks!

**Comment by wmdietl** [comment] 2015-09-16 22:01
I had a look at your stack trace to try to see whether I can reproduce the issue.
However, the documentation for LetExpr is not very helpful:

http://hg.openjdk.java.net/jdk8u/jdk8u-dev/langtools/file/f166261986cc/src/share/classes/com/sun/tools/javac/tree/JCTree.java#l2418

It is a synthetic tree node that seems to be used to introduce variables when handling lambda expressions. All test cases we have for lambda expressions work, so I'm not quite sure under which circumstances LetExpr is used.

If you could minimize your crashing example to something that you could send us, I could have another look at this issue.

Thanks!
cu, WMD.

**Comment by mernst** [comment] 2015-10-13 20:57
I'm reluctantly closing this issue because we don't have a test case to reproduce it.

If someone else can provide a concrete test case, we will gladly reopen the issue and fix the bug.

**Comment by pSub** [comment] 2018-03-29 08:41
Recently I stumbled upon this error when trying to use the checker framework for an internal project. I could come up with a minimal working example demonstrating the crash and have uploaded it to github (https://github.com/pSub/checker-framework-letexpr-crash) and setup a travis-ci job for demonstration (https://travis-ci.org/pSub/checker-framework-letexpr-crash).

It somehow has to do with the "+=" Operation on numbers and interfaces containing only one method declaration (ie. functional interfaces). I tried to document in the code what works and what doesn't. However I don't really understand what is happening. I hope you guys have a chance fixing the bug using this mininmal working example.

**Comment by wmdietl** [comment] 2018-03-29 12:43
Thanks for providing this test case! We'll look into fixing it.

**Comment by smillst** [comment] 2018-04-10 18:43
This is the FormatterChecker.

**Comment by wmdietl** [comment] 2018-05-28 02:14
@pSub Thanks a lot for creating this test case!
It was quite tricky to track down what the root source of the problem was. We didn't update internal compiler state in all the right places, which led to this strange exception in a very particular combination.
I now create #1998 with a simple-looking fix, which doesn't just prevent this exception, but also makes sure the right annotations are returned for certain classes.

**Closed** 2018-05-29 15:35 UTC
Labels: bug, crash
