### ISSUE TITLE
Error:java: AsSuperVisitor: Unexpected combination: type: TYPEVAR superType: ARRAY.

### ISSUE THREAD

**Issue by Pr0methean** [typetools/checker-framework#1531] opened 2017-09-21 20:15 UTC
I got this error message:
```
Error:java: AsSuperVisitor: Unexpected combination: type: TYPEVAR superType: ARRAY.
  type: capture#224 of ? extends byte[] extends @Initialized @NonNull byte @Initialized @NonNull []
  superType: @Initialized @NonNull byte @Initialized @NonNull []; The Checker Framework crashed.  Please report the crash.  To see the full stack trace invoke the compiler with -AprintErrorStack
```
by adding the following annotation to a method:
```
public final class SplittableRandomReseeder {
  private static @Nullable Field SEED_FIELD;

  /*...*/

  @EnsuresNonNullIf(expression = "SEED_FIELD", result = true)
  public static boolean canGetSeed() {
    return SEED_FIELD != null;
  }
}
```
Surrounding "SEED_FIELD" with curly brackets seems to work when SEED_FIELD is `@Nullable`, but not when I change it to `@MonotonicNonNull`.

**Comment by Pr0methean** [comment] 2017-09-21 20:21
The affected version is 2.2.0 from Maven Central.

**Comment by Pr0methean** [comment] 2017-09-21 20:25
Update: Even after removing the `@EnsuresNonNullIf` annotation, I still get a crash when processing the following method:
```
  public static byte[] getSeed(final SplittableRandom splittableRandom) {
    if (!canGetSeed()) {
      throw new UnsupportedOperationException();
    } else {
      try {
        assert SEED_FIELD != null : "@AssumeAssertion(nullness)";
        return BinaryUtils.convertLongToBytes((long) (SEED_FIELD.get(splittableRandom)));
      } catch (final IllegalAccessException e) {
        throw new RuntimeException(e);
      }
    }
  }
```

**Comment by Pr0methean** [comment] 2017-09-21 21:24
Versions 2.1.14, 2.1.7, 2.1.0 and 2.0.0 are also affected.

**Comment by smillst** [comment] 2017-09-21 21:36
I tried the following, but wasn't able to reproduce the crash:
```
import org.checkerframework.checker.nullness.qual.*;
public final class Issue1531{
  private static @Nullable Object SEED_FIELD;

  /*...*/

  @EnsuresNonNullIf(expression = "SEED_FIELD", result = true)
  public static boolean canGetSeed() {
    return SEED_FIELD != null;
  }
}
```

Can you please provide a reproducible test case?
The Checker Framework describes the information that the developers need:
https://checkerframework.org/manual/#reporting-bugs

**Comment by Pr0methean** [comment] 2017-09-22 08:28
@smillst Are you using Maven? That may make a difference, as it did on #1510

**Comment by smillst** [comment] 2017-09-22 15:08
No, I tried from the command line.  If you provide the exact instructions for reproducing the error, I  can try that.

**Comment by mernst** [comment] 2017-10-02 14:20
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2017-10-02 14:20 UTC
Labels: Unreproducible
