### ISSUE TITLE
Using Builder Class with Checker Annotations Throws Compiler Error contracts.precondition.not.satisfied On Use

### ISSUE THREAD

**Issue by jaloren** [typetools/checker-framework#4289] opened 2021-02-17 00:28 UTC
To reproduce this problem:

1. git clone git@github.com:jaloren/checker-builder-example.git
2. cd into the directory checker-builder-example
3. export JAVA_HOME environment variable to point to a JDK8 installation. Note I also reproduced this problem on JDK11 as well.
4. execute the following command: ./gradlew compileJava

The following errors are thrown:

```
/Users/jlorenzini/repos/exp/checker-builder-example/src/main/java/com/test/checker/builder/Application.java:9: error: [contracts.precondition.not.satisfied] precondition of new Person.Builder().setGender("male").setName("john doe").build is not satisfied.
            .build();
                  ^
  found   : no information about gender
  required: gender is @NonNull
/Users/jlorenzini/repos/exp/checker-builder-example/src/main/java/com/test/checker/builder/Application.java:9: error: [contracts.precondition.not.satisfied] precondition of new Person.Builder().setGender("male").setName("john doe").build is not satisfied.
            .build();
                  ^
  found   : no information about name
  required: name is @NonNull
2 errors
```

I believe the builder class has the appropriate checker annotations to prove this code is null safe. Please refer to this class for the annotations used: 

https://github.com/jaloren/checker-builder-example/blob/master/src/main/java/com/test/checker/builder/Person.java#L35

And actual usage of the builder here:

https://github.com/jaloren/checker-builder-example/blob/master/src/main/java/com/test/checker/builder/Application.java#L6

This could certainly be user error on my part since I may have missed appropriate annotations but I struggled to find any examples of doing a builder in the checker user guide. If I missed it by all means, please link me to an example :). 

I did look on the issue tracker but I only found https://github.com/typetools/checker-framework/issues/1770 which didn't seem to be the same problem.

**Comment by smillst** [comment] 2021-02-17 21:01
The problem is that the `@EnsuresNonNull` annotations don't ensure that the fields of the returned object are non-null.  See https://github.com/typetools/checker-framework/issues/2465#issuecomment-487219817 for the best explanation of the issue.  (This issue is a duplicate of #2465.)

**Comment by mernst** [comment] 2021-02-18 18:42
Closed as duplicate.  Thanks for the report, though!  We appreciate it.

**Closed by mernst** 2021-02-18 18:42 UTC
