### ISSUE TITLE
Crash report: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by kennknowles** [typetools/checker-framework#3794] opened 2020-10-17 02:45 UTC
Steps to reproduce:

```
git clone --depth 1 --branch checker-curiosity https://github.com/kennknowles/beam
cd beam
./gradlew compileJava
```

Output:

```
error: SourceChecker.typeProcess: unexpected Throwable (IndexOutOfBoundsException) while processing /Users/klk/GitHub/apache/beam/sdks/java/harness/src/main/java/org/apache/beam/fn/harness/AssignWindowsRunner.java; message: Index: 0, Size: 0
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /Users/klk/GitHub/apache/beam/sdks/java/harness/src/main/java/org/apache/beam/fn/harness/AssignWindowsRunner.java
  Last visited tree at line 42 column 1:
  class AssignWindowsRunner<T, W extends BoundedWindow> {
  Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0; java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
  	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
  	at java.util.ArrayList.get(ArrayList.java:433)
  	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
  	at org.checkerframework.framework.util.AnnotatedTypes.getAnnotatedTypes(AnnotatedTypes.java:949)
  	at org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism.resolve(AbstractQualifierPolymorphism.java:203)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.constructorFromUsePreSubstitution(GenericAnnotatedTypeFactory.java:1518)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.constructorFromUse(AnnotatedTypeFactory.java:2052)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.constructorFromUse(GenericAnnotatedTypeFactory.java:1507)
  	at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitNewClass(TypeFromExpressionVisitor.java:320)
  	at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitNewClass(TypeFromExpressionVisitor.java:70)
  	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1705)
  	at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
  	at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:38)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1288)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1023)
  	at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:217)
  	at org.checkerframework.framework.flow.CFAbstractTransfer.visitNode(CFAbstractTransfer.java:591)
  	at org.checkerframework.framework.flow.CFAbstractTransfer.visitNode(CFAbstractTransfer.java:94)
  	at org.checkerframework.dataflow.cfg.node.AbstractNodeVisitor.visitObjectCreation(AbstractNodeVisitor.java:333)
  	at org.checkerframework.framework.flow.CFAbstractTransfer.visitObjectCreation(CFAbstractTransfer.java:962)
  	at org.checkerframework.framework.flow.CFAbstractTransfer.visitObjectCreation(CFAbstractTransfer.java:94)
  	at org.checkerframework.dataflow.cfg.node.ObjectCreationNode.accept(ObjectCreationNode.java:63)
  	at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:338)
  	at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:375)
  	at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:152)
  	at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:106)
  	at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:109)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1296)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1204)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1615)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:293)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:318)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:171)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:916)
  	at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:502)
  	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:190)
```

**Comment by mernst** [comment] 2020-10-17 03:17
Thanks for the bug reports; we appreaciate them.

The "steps to reproduce" that you gave are identical for #3793 and #3794:  both are 

```
git clone --depth 1 --branch checker-curiosity https://github.com/kennknowles/beam
cd beam
./gradlew compileJava
```

Perhaps one or both of those is a typo.

Furthermore, when I run those commands, I get different output than in either of the issues you filed.

My output includes:

```
> Task :sdks:java:io:kudu:compileJava
error: SourceChecker.typeProcess: unexpected Throwable (CompletionFailure) while processing /home/mernst/tmp/beam/sdks/java/io/kudu/src/main/java/org/apache/beam/sdk/io/kudu/KuduIO.java; message: class file for org.apache.yetus.audience.InterfaceAudience$Private not found
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /home/mernst/tmp/beam/sdks/java/io/kudu/src/main/java/org/apache/beam/sdk/io/kudu/KuduIO.java
  Last visited tree at line 123 column 1:
  @Experimental(Kind.SOURCE_SINK)
  Exception: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.apache.yetus.audience.InterfaceAudience$Private not found; com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.apache.yetus.audience.InterfaceAudience$Private not found
error: SourceChecker.typeProcess: unexpected Throwable (CompletionFailure) while processing /home/mernst/tmp/beam/sdks/java/io/kudu/src/main/java/org/apache/beam/sdk/io/kudu/KuduServiceImpl.java; message: class file for org.apache.yetus.audience.InterfaceStability not found
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /home/mernst/tmp/beam/sdks/java/io/kudu/src/main/java/org/apache/beam/sdk/io/kudu/KuduServiceImpl.java
  Last visited tree at line 48 column 1:
  @SuppressWarnings("nullness")
  Exception: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.apache.yetus.audience.InterfaceStability not found; com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.apache.yetus.audience.InterfaceStability not found
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

Can you please correct the "steps to reproduce" and give more specifics, such as the whole log which will show which gradle task failed?  (That would help me run a more targeted build to reproduce your problem, or to understand what is different about our environments.)

Thanks again.

**Comment by kennknowles** [comment] 2020-10-17 03:38
The steps to reproduce are, in fact, identical. It is interesting that you get different output. I will circle back to each of these issues and confirm when I get the chance.

Essentially at each step of my process producing https://github.com/apache/beam/pull/13134 I get a number of errors in my project to suppress, and a number of crashes. Then I make a copy of the branch, push it up, and report each issue that seems potentially distinct. I have gotten a bit lazy about which ones are truly distinct so in that PR you can search for `classesThatTriggerCheckerBugs` to see which classes I have suppressed, and which checker issues I have decided to associate them with.

**Comment by smillst** [comment] 2020-10-20 18:11
This is a duplicate of #3776.

**Closed by smillst** 2020-10-20 18:11 UTC
