### ISSUE TITLE
Under parallel compilation, checker-framework can fail with a NullPointerException

### ISSUE THREAD

**Issue by mikeb01** [typetools/checker-framework#2244] opened 2019-01-17 21:54 UTC
We currently use the checker framework (2.5.8) within buck (see #2164 for a similar issue and sample project).  Buck creates a thread pool of JavacTaskImpls and in the more recent release (2019.01.10.01) the isolation between the compilers has changed such that, in some circumstances checker framework fails with a NullPointerException.

Code being compiled:
```
public class BigDecimalAsPlainStringSerialiser implements JsonSerializer<BigDecimal>
{
    @Override
    public JsonElement serialize(final BigDecimal toSerialise, final Type typeOfSrc, final JsonSerializationContext context)
    {
        return new JsonPrimitive(toSerialise.toPlainString());
    }
}
```

StackTrace:
```
Command failed with exit code 1.
stderr: : error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing /home/barkerm/sources/lmax/buck-all/infrastructure/webapps/api-json/src/main/java/com/lmax/ui/common/codec/json/BigDecimalAsPlainStringSerialiser.java

  Compilation unit: /home/barkerm/sources/lmax/buck-all/infrastructure/webapps/api-json/src/main/java/com/lmax/ui/common/codec/json/BigDecimalAsPlainStringSerialiser.java
  Last visited tree at line 13 column 5:
      @Override
  Exception: java.lang.NullPointerException; Stack trace: com.sun.tools.javac.jvm.ClassReader.createBadClassFileDiagnostic(ClassReader.java:348)
  com.sun.tools.javac.jvm.ClassReader.access$100(ClassReader.java:76)
  com.sun.tools.javac.jvm.ClassReader$BadClassFile.<init>(ClassReader.java:343)
  com.sun.tools.javac.jvm.ClassReader.badClassFile(ClassReader.java:357)
  com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2290)
  com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2511)
  com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2442)
  com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
  com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
  com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
  com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
  com.sun.tools.javac.code.Symbol$ClassSymbol.members(Symbol.java:978)
  com.sun.tools.javac.model.AnnotationProxyMaker.getAllValues(AnnotationProxyMaker.java:123)
  com.sun.tools.javac.model.AnnotationProxyMaker.getAllReflectedValues(AnnotationProxyMaker.java:100)
  com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:88)
  com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:79)
  com.sun.tools.javac.code.AnnoConstruct.getAnnotation(AnnoConstruct.java:179)
  org.checkerframework.framework.util.DefaultAnnotationFormatter.isInvisibleQualified(DefaultAnnotationFormatter.java:26)
  org.checkerframework.framework.util.DefaultAnnotationFormatter.formatAnnotationString(DefaultAnnotationFormatter.java:48)
  org.checkerframework.checker.units.UnitsAnnotatedTypeFormatter$UnitsAnnotationFormatter.formatAnnotationString(UnitsAnnotatedTypeFormatter.java:77)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter$FormattingVisitor.visitDeclared(DefaultAnnotatedTypeFormatter.java:203)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter$FormattingVisitor.visitDeclared(DefaultAnnotatedTypeFormatter.java:91)
  org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.accept(AnnotatedTypeMirror.java:849)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter$FormattingVisitor.visit(DefaultAnnotatedTypeFormatter.java:182)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter$FormattingVisitor.visitExecutable(DefaultAnnotatedTypeFormatter.java:272)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter$FormattingVisitor.visitExecutable(DefaultAnnotatedTypeFormatter.java:91)
  org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedExecutableType.accept(AnnotatedTypeMirror.java:1028)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter$FormattingVisitor.visit(DefaultAnnotatedTypeFormatter.java:176)
  org.checkerframework.framework.type.DefaultAnnotatedTypeFormatter.format(DefaultAnnotatedTypeFormatter.java:81)
  org.checkerframework.framework.type.AnnotatedTypeMirror.toString(AnnotatedTypeMirror.java:688)
  org.checkerframework.common.basetype.BaseTypeVisitor$OverrideChecker.<init>(BaseTypeVisitor.java:2757)
  org.checkerframework.common.basetype.BaseTypeVisitor.createOverrideChecker(BaseTypeVisitor.java:2455)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkOverride(BaseTypeVisitor.java:2521)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkOverride(BaseTypeVisitor.java:2490)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:578)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:159)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
  org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:91)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:272)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:159)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
  com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
  org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:97)
  org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:350)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:310)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:159)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:85)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:967)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:494)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  com.facebook.buck.jvm.java.plugin.adapter.JavacTaskWrapper.call(JavacTaskWrapper.java:100)
  com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTask.call(BuckJavacTask.java:52)
  com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskProxyImpl.call(BuckJavacTaskProxyImpl.java:134)
  com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.lambda$startCompiler$2(Jsr199JavacInvocation.java:421)
  com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
  com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
Errors: 1. Warnings: 0.
```
Build command (this is not the actual instance that triggered the behaviour, but the command used with version and AprintAllQualifiers prepended to the args):
```
javac -version -AprintAllQualifiers -source 8 -target 8 -sourcepath  -g -processorpath /home/barkerm/sources/lmax/buck-all/buck-out/gen/exchange/kernels/account-types/lib__account-types__output/account-types.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/exchange/quantisation/annotated-types-kernel/lib__annotated-types-kernel__output/annotated-types-kernel.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/infrastructure/time-annotations/lib__time-annotations__output/time-annotations.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/lib/__checker-framework__/checker-2.5.8.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/lib/__joda-convert__/joda-convert-2.0.1.jar -processor org.checkerframework.checker.units.UnitsChecker -Anocheckjdk -Aunits=com.lmax.instrument.Price,com.lmax.instrument.UnitQty,com.lmax.instrument.Cost,com.lmax.instrument.ContractQty,com.lmax.instrument.Tier,com.lmax.time.annotations.Microseconds,com.lmax.time.annotations.Milliseconds,com.lmax.instrument.SecurityId,com.lmax.instrument.InstrumentId,com.lmax.instrument.OrderBookId,com.lmax.instrument.ExternalOrderBookId -Werror -verbose -d /home/barkerm/sources/lmax/buck-all/buck-out/bin/infrastructure/webapps/api-json/lib__webapps-api-json__scratch/classes -s /home/barkerm/sources/lmax/buck-all/buck-out/annotation/infrastructure/webapps/api-json/__webapps-api-json_gen__ -classpath /home/barkerm/sources/lmax/buck-all/buck-out/gen/exchange/kernels/account-types/lib__account-types__output/account-types.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/exchange/quantisation/annotated-types-kernel/lib__annotated-types-kernel__output/annotated-types-kernel.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/infrastructure/time-annotations/lib__time-annotations__output/time-annotations.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/lib/__checker-framework__/checker-2.5.8.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/lib/__google-gson__/gson-2.3.1.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/lib/__joda-convert__/joda-convert-2.0.1.jar:/home/barkerm/sources/lmax/buck-all/buck-out/gen/lib/__slf4j-api__/slf4j-api-1.7.25.jar @buck-out/gen/infrastructure/webapps/api-json/__webapps-api-json__srcs
```
[Output from the above command](https://github.com/typetools/checker-framework/files/2770701/out.txt)

**Comment by mernst** [comment] 2019-03-28 19:24
I'm sorry you are having this problem.
javac is crashing while trying to look up the @InvisibleQualifier meta-annotation on some annotation.
I'm not sure which one, but likely one of the ones you supplied via command-line arguments.  You could find out by printing local variable annoElement at this line:
https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/util/DefaultAnnotationFormatter.java#L25

The error suggests that the annotation is not available (on the classpath, processorpath, or wherever javac is looking for it).
In general, javac does not require all meta-annotations to be available.  When one is not available, javac may make up some incomplete information.  However, the Checker Framework try to use that proxy -- for example, to look up meta-annotations.

My guess is that your annotations are defined in `/home/barkerm/sources/lmax/buck-all/buck-out/gen/infrastructure/time-annotations/lib__time-annotations__output/time-annotations.jar`, which is on the classpath and processorpath.  I'm not sure where else you would need to put them.
Are they all there, and might that file be getting regenerated so that it was momentarily not available?  (Those are just guesses.)

It's hard for me to debug this remotely, but maybe this helps you, especially in knowing where to add diagnostic output.

**Comment by mikeb01** [comment] 2019-03-30 22:22
The thing that makes this tricky is that it works perfectly if I limit the build to a single thread.  There seems to be something the annotation resolution that does not appear to be thread safe.  I'm not sure if it is in the checker framework or the Javac library.  Running it multiple times shows the error occur in different seemingly random) places.

We've worked around this for now (pulled checker our of our main commit build and run it Jenkins target, single threaded so it won't fail).  I'll need to do a deeper dive into the issue at some later point.

**Comment by mernst** [comment] 2019-03-31 00:55
Thanks for the update.

The crash is in javac, which makes me suspect it, but the problem could be in the Checker Framework too.

When you get back to this, please let us know how we can help you.

**Comment by mernst** [comment] 2019-04-12 02:22
I'm going to close this for now -- not because it isn't important, but because we cannot make progress on it without reproducing it.  As soon as we have more information about what is happening, we would be happy to fix it.  Thanks in advance to anyone who can provide more information.

**Closed by mernst** 2019-04-12 02:22 UTC
Labels: Unreproducible
