### ISSUE TITLE
Undetected NPE in method with parameter type "List<? extends List<Object>>"

### ISSUE THREAD

**Issue by sebright** [typetools/checker-framework#1838] opened 2018-02-15 20:39 UTC
This is a simplified example of an issue that appeared in [opencensus-java](https://github.com/census-instrumentation/opencensus-java) (https://github.com/census-instrumentation/opencensus-java/pull/998#issuecomment-366015863) with Checker Framework version 2.3.2.

The Nullness Checker passes, but the program throws a NPE when it calls `element.toString()` on the null element that was inserted in `f()`.

```java
import java.util.ArrayList;
import java.util.List;
import org.checkerframework.checker.nullness.qual.Nullable;

public class Example {
  public static void main(String[] args) {
    f();
  }

  public static void f() {
    List<@Nullable Object> list = new ArrayList<@Nullable Object>();
    list.add(null);
    List<List<@Nullable Object>> listList = new ArrayList<List<@Nullable Object>>();
    listList.add(list);
    processElements(listList);
  }

  private static void processElements(List<? extends List<Object>> listList) {
    for (List<Object> list : listList) {
      for (Object element : list) {
        element.toString();
      }
    }
  }
}
```

This also passes in the live demo ([link](http://eisop.uwaterloo.ca/live/#mode=display&code=import+java.util.ArrayList%3B%0Aimport+java.util.List%3B%0Aimport+org.checkerframework.checker.nullness.qual.Nullable%3B%0A%0Apublic+class+Example+%7B%0A++public+static+void+main(String%5B%5D+args)+%7B%0A++++f()%3B%0A++%7D%0A%0A++public+static+void+f()+%7B%0A++++List%3C%40Nullable+Object%3E+list+%3D+new+ArrayList%3C%40Nullable+Object%3E()%3B%0A++++list.add(null)%3B%0A++++List%3CList%3C%40Nullable+Object%3E%3E+listList+%3D+new+ArrayList%3CList%3C%40Nullable+Object%3E%3E()%3B%0A++++listList.add(list)%3B%0A++++processElements(listList)%3B%0A++%7D%0A%0A++private+static+void+processElements(List%3C%3F+extends+List%3CObject%3E%3E+listList)+%7B%0A++++for+(List%3CObject%3E+list+%3A+listList)+%7B%0A++++++for+(Object+element+%3A+list)+%7B%0A++++++++element.toString()%3B%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D&typeSystem=nullness)).

Removing "`? extends`" from `processElements`'s parameter causes the check to fail at the call to `processElements`, as I expected ([link](http://eisop.uwaterloo.ca/live/#mode=display&code=import+java.util.ArrayList%3B%0Aimport+java.util.List%3B%0Aimport+org.checkerframework.checker.nullness.qual.Nullable%3B%0A%0Apublic+class+Example+%7B%0A++public+static+void+main(String%5B%5D+args)+%7B%0A++++f()%3B%0A++%7D%0A%0A++public+static+void+f()+%7B%0A++++List%3C%40Nullable+Object%3E+list+%3D+new+ArrayList%3C%40Nullable+Object%3E()%3B%0A++++list.add(null)%3B%0A++++List%3CList%3C%40Nullable+Object%3E%3E+listList+%3D+new+ArrayList%3CList%3C%40Nullable+Object%3E%3E()%3B%0A++++listList.add(list)%3B%0A++++processElements(listList)%3B%0A++%7D%0A%0A++private+static+void+processElements(List%3CList%3CObject%3E%3E+listList)+%7B%0A++++for+(List%3CObject%3E+list+%3A+listList)+%7B%0A++++++for+(Object+element+%3A+list)+%7B%0A++++++++element.toString()%3B%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D&typeSystem=nullness)):

No. | Type | Description | Line | Column
-- | -- | -- | -- | --
1 | error | `Error: [argument.type.incompatible] incompatible types in argument.   found   : @Initialized @NonNull List<@Initialized @NonNull List<@Initialized @Nullable Object>>   required: @Initialized @NonNull List<@Initialized @NonNull List<@Initialized @NonNull Object>>` | 15 | 21

**Comment by wmdietl** [comment] 2018-02-15 22:38
Thanks for providing this test case!
The call to `processElements(listList);` should raise an error, as the argument `List<List<@Nullable Object>>` should not be a subtype of `List<? extends List<Object>>`.

**Comment by smillst** [comment] 2018-02-27 18:48
This seems to be a duplicate of #849.

**Closed** 2018-04-13 22:38 UTC
Labels: FalseNegative (missing warning or unsoundness)

**Comment by sebright** [comment] 2018-04-13 22:49
Thanks!
