### ISSUE TITLE
surprising 'incompatible types in assignment' error

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#471] opened 2015-09-12 06:16 UTC
```java
import javax.annotation.Nullable;

class Test<T> {
  @Nullable T t;
  Test(@Nullable T t) {
    this.t = t;
  }
}
```

```
$ ~/jsr308/checker-framework-1.9.5/checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker -version Test.java
javac 1.8.0-jsr308-1.9.5
F.java:5: error: [assignment.type.incompatible] incompatible types in assignment.
    this.t = t;
             ^
  found   : T extends @Initialized @Nullable Object
  required: T extends @Initialized @Nullable Object
1 error
```

**Comment by JonathanBurke** [comment] 2015-09-14 18:03
This is an interesting error.  It seems to occur only when the javax.annotation.Nullable is used (and not the Checker Framework nullable).

What's also interesting is that when we typecheck using the commandline arguments:
`-AprintVerboseGenerics -AprintAllQualifiers`

We get the following message:
```
/Users/jburke/Documents/tmp/Issue471.java:7: error: [assignment.type.incompatible] incompatible types in assignment.
    this.t = t;
             ^
  found   : T[ extends @Initialized @Nullable Object super @Initialized @Nullable Void]
  required: T[ extends @Initialized @Nullable Object super @Initialized @NonNull Void]
```

This seems like it might be an issue with our annotation aliasing mechanism, which maps common annotations to Checker Framework annotations.

**Comment by smillst** [comment] 2016-03-11 20:51
Same error with caching turned off.

**Comment by smillst** [comment] 2016-06-09 16:03
#783  is a duplicate of this issue.

**Closed** 2016-06-09 18:08 UTC
Labels: bug
