### ISSUE TITLE
InvocationTargetException using the SubtypingChecker in 2.1.12

### ISSUE THREAD

**Issue by DavidBriant** [typetools/checker-framework#1329] opened 2017-06-08 18:07 UTC
Hi,

I'm getting the following error:

Error:java: InvocationTargetException when invoking constructor for class org.checkerframework.common.subtyping.SubtypingAnnotatedTypeFactory; Underlying cause: AnnotatedTypeFactory: invalid qualifier hierarchy: class org.checkerframework.framework.util.GraphQualifierHierarchy Supertypes Graph: 
  Supertypes Map: 
  Tops: []
  Bottoms: []; invoke the compiler with -AprintErrorStack to see the stack trace.

I've based my code on the example in the on-line manual.

Project A:

```
package annotations;

import org.checkerframework.framework.qual.DefaultQualifierInHierarchy;
import org.checkerframework.framework.qual.SubtypeOf;

import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

@DefaultQualifierInHierarchy
@SubtypeOf ({})
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
public @interface Untyped {}
```

and

```
package annotations;

import org.checkerframework.framework.qual.*;

import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

@SubtypeOf (Untyped.class)
@ImplicitFor (literals={LiteralKind.NULL})
@DefaultFor ({TypeUseLocation.LOWER_BOUND})
@Target ({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
public @interface  Issuer {}
```

Project B:

```
import annotations.Untyped;
 
public class CheckerFrameWorkTest {

    void test() {
        @Untyped String a = "hello";
    }
}
```
Project A compiles ok. Compiling Project B causes the problems.

Running on Windows, IntelliJ community 2016.3, with Maven.

Any ideas?

Kind regards

David

PS Here's the error stack:

```
Error:java: InvocationTargetException when invoking constructor for class org.checkerframework.common.subtyping.SubtypingAnnotatedTypeFactory; Underlying cause: AnnotatedTypeFactory: invalid qualifier hierarchy: class org.checkerframework.framework.util.GraphQualifierHierarchy Supertypes Graph: 
  Supertypes Map: 
  Tops: []
  Bottoms: []
  Exception: java.lang.reflect.InvocationTargetException; Stack trace: sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:231)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:186)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:207)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:83)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:854)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:98)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:811)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:160)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:180)
  org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:463)
  org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:319)
  org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:231)
  org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:193)
  org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1282)
  org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:956)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1028)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:915)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:741)
  org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:195)
  org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
  org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:238)
  org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
  Underlying Exception: org.checkerframework.framework.source.SourceChecker$CheckerError: AnnotatedTypeFactory: invalid qualifier hierarchy: class org.checkerframework.framework.util.GraphQualifierHierarchy Supertypes Graph: 
  Supertypes Map: 
  Tops: []
  Bottoms: []; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.AnnotatedTypeFactory.createQualifierHierarchy(AnnotatedTypeFactory.java:615)
  org.checkerframework.framework.type.AnnotatedTypeFactory.createQualifierHierarchy(AnnotatedTypeFactory.java:557)
  org.checkerframework.framework.type.AnnotatedTypeFactory.postInit(AnnotatedTypeFactory.java:446)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.postInit(GenericAnnotatedTypeFactory.java:202)
  org.checkerframework.common.subtyping.SubtypingAnnotatedTypeFactory.<init>(SubtypingAnnotatedTypeFactory.java:15)
  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:231)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:186)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:207)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:83)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:854)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:98)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:811)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:160)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:180)
  org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:463)
  org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:319)
  org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:231)
  org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:193)
  org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1282)
  org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:956)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1028)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:915)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:741)
  org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:195)
  org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
  org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:238)
  org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
  Underlying Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.AnnotatedTypeFactory.createQualifierHierarchy(AnnotatedTypeFactory.java:615)
  org.checkerframework.framework.type.AnnotatedTypeFactory.createQualifierHierarchy(AnnotatedTypeFactory.java:557)
  org.checkerframework.framework.type.AnnotatedTypeFactory.postInit(AnnotatedTypeFactory.java:446)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.postInit(GenericAnnotatedTypeFactory.java:202)
  org.checkerframework.common.subtyping.SubtypingAnnotatedTypeFactory.<init>(SubtypingAnnotatedTypeFactory.java:15)
  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:258)
  org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:231)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:186)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:207)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:83)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:854)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:98)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:811)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:160)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:180)
  org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:463)
  org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:319)
  org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:231)
  org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:193)
  org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1282)
  org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:956)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1028)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:915)
  org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:741)
  org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:195)
  org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
  org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:238)
  org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
```

**Comment by smillst** [comment] 2017-06-08 18:13
Sorry you're having trouble.  What is the exact command and/or steps you used to compile Project B?  I would guess that something is wrong with that command.

**Comment by wmdietl** [comment] 2017-06-08 22:01
In particular, are you passing the `-Aquals=annotations.Untyped,annotations.Issuer` or the `-AqualDirs` command-line flags, as outlined here: https://checkerframework.org/manual/#subtyping-using ?

**Comment by DavidBriant** [comment] 2017-06-09 06:34
Thx for getting back:

-classpath /.../ProjectA/target/classes
-Xbootclasspath/p:c:/Users/David/.m2/repository/org/checkerframework/jdk8/2.1.12/jdk8-2.1.12.jar
-AqualDirs=/.../ProjectA/target/classes
-AprintErrorStack

**Comment by smillst** [comment] 2017-06-09 15:29
What are the contents of `/.../ProjectA/target/classes`?  It should be `annotations/Issuer.class` and `annotations/Untyped.java`.  From the error message ` could not load class for annotation: type_utils.annotations.Untyped`, I would guess that is is `type_utils/annotations/Untyped.class`.

**Comment by mernst** [comment] 2017-07-05 19:13
I'm closing this because we didn't hear back from the original poster.
If we get enough information to understand and reproduce it, then we can re-open it.

**Closed by mernst** 2017-07-05 19:13 UTC

**Comment by olegz-circle** [comment] 2019-06-20 21:09
Hey @mernst, @wmdietl , it's an old thread but can't find anything more relevant. Have the same problem as @DavidBriant
```
org.checkerframework.common.subtyping.SubtypingAnnotatedTypeFactory; Underlying cause: AnnotatedTypeFactory: invalid qualifier hierarchy: class org.checkerframework.framework.util.GraphQualifierHierarchy Supertypes Graph: 
[ERROR]   Supertypes Map: 
[ERROR]   Tops: []
[ERROR]   Bottoms: []
```
Here is maven [project](https://github.com/olegz-circle/checker-subtyping) with code from [tutorial](https://github.com/typetools/checker-framework/tree/master/docs/tutorial/src/encrypted)

to reproduce execute `mvn clean compile`

**Comment by mernst** [comment] 2019-06-20 23:15
Thanks for the simple test case.  That helps a lot!

I have improved the Checker Framework diagnostics, so now the error message that you get reads:

[ERROR] No qualifiers found in checker-subtyping/target/classes

That directory is empty at the time the type-checker is run, which is the reason for the failure.

**Comment by mernst** [comment] 2019-06-20 23:17
By the way, the [documentation for the Subtyping Checker](https://checkerframework.org/manual/#subtyping-using) says:

> The annotations listed in `-Aquals` must be accessible to the compiler during compilation in the classpath. In other words, they must already be compiled (and, typically, be on the javac classpath) before you run the Subtyping Checker with javac. It is not sufficient to supply their source files on the command line.

It's good to have a clearer diagnostic, though, so your report was very useful.
