### ISSUE TITLE
DefaultQualifier(NonNull.class) gets @Nullable "this"

### ISSUE THREAD

**Issue by kornevgen** [typetools/checker-framework#1414] opened 2017-07-19 20:34 UTC
Nullness Checker (2.1.13) doesn't allow `getClass()` invocation in the following code (it seems `this` object is considered as `@Nullable`):

    import org.checkerframework.checker.nullness.qual.*;
    
    @org.checkerframework.framework.qual.DefaultQualifier(Nullable.class)
    public class X {
        public @NonNull Object cls() {
            return getClass();
        }
    }

> `Error: [method.invocation.invalid] call to getClass() not allowed on the given receiver.`
> `found : @Initialized @Nullable Object`
> `required: @UnknownInitialization @NonNull Object`

**Comment by smillst** [comment] 2017-07-19 20:38
Thanks for reporting!  This is a duplicate of #1268, so I'm going to close this issue.  There's a work around mentioned here: https://github.com/typetools/checker-framework/issues/1268#issuecomment-300010732.

**Closed by smillst** 2017-07-19 20:38 UTC
