### ISSUE TITLE
NPE in checked code

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#1954] opened 2018-04-23 12:38 UTC
This test is compilable with CF enabled and produce NPE 
```
public class NPETest {
    public interface Getter<R>{
        R get();
    }

    public interface NullStringGetter extends Getter<@Nullable String>{}

    public <T, R> Getter<R> transform(Function<Stream<T>, R> fn, Getter<T> getter){
        return () -> fn.apply(Stream.of(getter.get()));
    }

    public static <T> @Nullable T fn (Stream<T> arg){
        return arg.findFirst().orElse(null);
    }

    @Test
    public void doo(){
        NullStringGetter nullStringGetter = () -> null;
        transform(NPETest::fn, nullStringGetter).get();
    }
}

```

**Comment by smillst** [comment] 2018-04-23 17:39
Thanks for reporting this.  The problem is that the Checker Framework does not yet support Java 8 type inference, see #979.  (We are actively working to fix this.) If you pass `-AconservativeUninferredTypeArguments` you will see the following:
```
NPETest.java:21: warning: [methodref.inference.unimplemented] This version of the Checker Framework does not type-check method references with implicit type arguments.
        transform(NPETest::fn, nullStringGetter).get();
                  ^
NPETest.java:21: warning: [methodref.inference.unimplemented] This version of the Checker Framework does not type-check method references with implicit type arguments.
        transform(NPETest::fn, nullStringGetter).get();
```

**Comment by justmin** [comment] 2018-04-25 15:16
Ok, but IMHO CF should be a little more conservative: it could produce false-positive errors but should not skip false-negative situations, NPE is unacceptable in any cases.

**Comment by smillst** [comment] 2018-05-01 22:04
I've add this as an additional test case for #979.  I'm closing this issue in favor of #979.

**Closed by smillst** 2018-05-01 22:04 UTC
