### ISSUE TITLE
Both with CF, gradle 5+ much slower than gradle 4

### ISSUE THREAD

**Issue by entonio** [typetools/checker-framework#3300] opened 2020-05-11 03:13 UTC
Hi.
This is not a bug report, it's a question on what I should investigate before opening one.
(It's a copy of https://github.com/kelloggm/checkerframework-gradle-plugin/issues/63)

I'm trying to migrate a number of projects to more recent libs and JDK, as mentioned elsewhere.

I have a project (no modules, no subprojects) that spends 85s on compileJava with Gradle 4.x. It takes 325s with Gradle 5 and 6. If not using the CF, it takes 29s in either Gradle. These measurings were very consistent, down to the second. I've tried changing a number of other factors, but the relevant one is the combination of the CF with Gradle 5+. I should mention these are numbers for JDK 8. With JDK 11 (source level 8), the numbers are 115s (Gradle 4), 135s (Gradle 5 and 6), and 35s (no CF) -- so, not the same magnitude of slowerness.

Where could the problem be? How can I debug it?

**Comment by kelloggm** [comment] 2020-05-11 19:44
Sorry we missed your previous post! Unfortunately, I don't really have much more information than you do.

One possibility is https://github.com/typetools/checker-framework/issues/2401, but that concerns something the Checker Framework *doesn't* do (support incremental compilation for Gradle projects). However, that change in Gradle happened in version 4.7, so the support for incremental processors on Gradle's end might be the problem.

**Comment by mernst** [comment] 2020-05-13 04:46
Your bug report is from a few releases ago.  Could you please confirm that you have the same problem when using the latest release of the Checker Framework and of the Checker Framework Gradle Plugin?

Could you help to determine whether the problem is with Gradle, with the Checker Framework, or with both?  Could you run Gradle with `--debug` to obtain the `javac` command line (it contains `-processor`), then time that command on both Java 8 and Java 11?  That will show how much of the time is due to the Checker Framework.

You point out that the slowdown on JDK 8 when using Gradle 4 vs 5/6 is ridiculous.  Are you also concerned about the slowdown from 115s to 135s when using JDK 11?  Or are you only concerned about JDK 8?

**Comment by mernst** [comment] 2020-06-15 21:55
I'm closing this because we didn't hear back with sufficient information to reproduce the problem.

**Closed by mernst** 2020-06-15 21:55 UTC
