### ISSUE TITLE
Exception in CF

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#1941] opened 2018-04-06 11:43 UTC
I use CheckerFramework in generated code.
I generate utility classes for user classes with some suffix, for ex. MyClass -> MyClassGeneratedUtilityClass
I disable CF for generated code using construction (in maven)
```
                    <compilerArguments>
                        <AskipDefs>GeneratedUtilityClass</AskipDefs>
                        <AprintErrorStack/>
                    </compilerArguments>

```

Sometimes exception occurred during parallel maven build (mvn -T 1C) - 1 out of 4-5 maven runs
```
InvocationTargetException when invoking constructor for class org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory; Underlying cause: java.lang.AssertionError: A reference was unexpectedly null.
  Exception: java.lang.reflect.InvocationTargetException; Stack trace: sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:260)
  org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:232)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:189)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:209)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:81)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:854)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:96)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:87)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:811)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:160)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
  org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
  org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
  org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
  org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
  Underlying Exception: java.lang.AssertionError: A reference was unexpectedly null.; Stack trace: com.github.javaparser.utils.Utils.assertNotNull(Utils.java:55)
  com.github.javaparser.TokenRange.<init>(TokenRange.java:19)
  com.github.javaparser.GeneratedJavaParserBase.range(GeneratedJavaParserBase.java:84)
  com.github.javaparser.GeneratedJavaParser.StubUnit(GeneratedJavaParser.java:255)
  com.github.javaparser.JavaParser.parse(JavaParser.java:134)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:491)
  com.github.javaparser.JavaParser.parseStubUnit(JavaParser.java:325)
  com.github.javaparser.JavaParser.parseStubUnit(JavaParser.java:338)
  org.checkerframework.framework.stub.StubParser.<init>(StubParser.java:179)
  org.checkerframework.framework.type.AnnotatedTypeFactory.parseStubFiles(AnnotatedTypeFactory.java:2931)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.postInit(GenericAnnotatedTypeFactory.java:235)
  org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.<init>(KeyForAnnotatedTypeFactory.java:68)
  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:260)
  org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:232)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:189)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:209)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:81)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:854)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:96)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:87)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:811)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:160)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
  org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
  org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
  org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
  org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
```

**Comment by wmdietl** [comment] 2018-04-06 13:54
Does this only happen if you use `skipDefs`?
Or is this a duplicate of #1771 ?

**Comment by justmin** [comment] 2018-04-06 15:38
I'm not sure, but mostly probably yes.
I had about 50 modules, 20 of them use CF. There was no problem 
I modified about 5 of CF-enabled modules this way:
- add another annotation processor which generate source code
- skipDefs for all generated code
and now error occasionally occurs in this 5 modules only. 
I'm not sure about parallelism of build, because total build takes too long. I'll check this on Monday.
I don't think it is a duplicate of #1771 because each time I saw exception about NativeConstructorAccessorImpl and 1771 not.

**Comment by justmin** [comment] 2018-04-09 06:11
This error occured with CF 2.3.1
I switched to CF 2.5.0 and now it looks it is fixed. Let's wait a couple of day before closing issue.

**Comment by justmin** [comment] 2018-04-09 07:35
Unfortunately switching to 2.5.0 didn't help - error still occures sometimes

**Comment by smillst** [comment] 2018-04-09 21:55
This is a problem with the StubParser.  The Nullness Checker only parsed flow.astub. 23b1deb removed flow.astub, so the crash reported here shouldn't happen anymore. (Unless you are using your own stub files.)  This was changed after 2.5.0 was released, so you can try compiling from source or wait for the next release.

**Comment by mernst** [comment] 2018-04-10 18:09
I think the problem is now resolved.
You can re-open this if the next release does not solve the problem, and you are not using stub files.
If you are using stub files, see issue #1771 which remains open.
Thanks for the bug report!

**Closed by mernst** 2018-04-10 18:09 UTC

**Comment by justmin** [comment] 2018-04-10 20:26
Please point me to some doc about stub files, I'm not sure what it is and whether I use it. 
Thank you in advance.

**Comment by smillst** [comment] 2018-04-10 20:28
https://checkerframework.org/manual/#stub-using
