### ISSUE TITLE
type refinement feature request

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1435] opened 2017-08-04 18:15 UTC
This is boiled down from a real-world example. It would be nice if the checker could tell that `t` is true iff `a` is non-null:

```java
import org.checkerframework.checker.nullness.qual.Nullable;
class Test {
  boolean f(@Nullable Long a, @Nullable Long b) {
    boolean t = a != null;
    //  dereference of possibly-null reference a
    return t && !a.equals(b);
  }
}
```

**Comment by mernst** [comment] 2017-08-04 18:28
I agree that this would be nice to support.  I have also seen it in real-world code.

This is possible to express in an extension to our type system.

There is a slippery slope toward increasing complexity and expressiveness of the type system, and this is definitely somewhere on that slope!  That's why we haven't implemented it yet.

**Comment by wmdietl** [comment] 2017-08-04 18:40
@cushon this looks like a duplicate of #406 which you also filed :-)

**Closed** 2017-08-04 18:41 UTC
Labels: enhancement
