### ISSUE TITLE
Getting "java.lang.AssertionError: this type of tree is unexpected here"

### ISSUE THREAD

**Issue by ariannab** [typetools/checker-framework#1688] opened 2017-11-28 15:20 UTC
This is the command I run from the command line:

`javac -processor org.checkerframework.checker.formatter.FormatterChecker -AsuggestPureMethods -AcheckPurityAnnotations -version -verbose -AprintErrorStack -AprintAllQualifiers -classpath "./bin/freecol-0.11.6.jar" ./src/freecol-0.11.6/src/net/sf/freecol/common/model/Player.java`

You can download freecol-0.11.6.jar from here:
https://goo.gl/YnXQf2

And sources from here:
https://goo.gl/XLUJAC

The output I get is attached as a `txt` file.
[freecol_issue.txt](https://github.com/typetools/checker-framework/files/1510418/freecol_issue.txt)

I get the same issue with other classes of the same project, such as `freecol-0.11.6/src/net/sf/freecol/common/model/Unit.java.` Instead, I tried the same command on classes from other different Java 6, 7 and 8 projects, without getting a single error. 
I searched for reports of similar errors, but I couldn't find any information about it.

**Comment by smillst** [comment] 2017-11-28 16:29
Thanks for reporting this error!
Are you using version 2.2.2 of the Checker Framework?  We have rewritten the class that is throwing the assertion error since the last release and I can't reproduce it using master.  So, it looks like this error has already been fixed, so I'm going to close this issue.

**Closed by smillst** 2017-11-28 16:29 UTC

**Comment by ariannab** [comment] 2017-11-28 16:43
Yes, as can be seen from the attached txt file, it is version 2.2.2. Now I'm building the tool from the latest source, I'll see if the error occurs again. 
Thanks for the reply!
