### ISSUE TITLE
Support for Guava Suppliers

### ISSUE THREAD

**Issue by rcchan** [typetools/checker-framework#1450] opened 2017-08-16 16:13 UTC
```
import org.checkerframework.checker.initialization.qual.UnderInitialization;
import org.checkerframework.checker.nullness.qual.RequiresNonNull;
import com.google.common.base.Supplier;

class Foo {
    private final Object o;
    private final Supplier<String> s;
    Foo() {
        o = new Object();
        s = a();
    }
    
    private Supplier<String> a(@UnderInitialization Foo this) {
        // Adding this in doesn't change the output despite o being final
        // (implied monotonic nonnull?)
        // @RequiresNonNull on this method doesn't help either.
        if (o == null) throw new NullPointerException();

        return new Supplier<String>() {  // () -> o.toString();
            // get() isn't called anywhere in the constructor
            // By the time the supplier is fully initialized, the constructor
            // is finished, and `o` is guaranteed to be NonNull
            public String get() {
                // Null check here does remove the error, but shouldn't be necessary?
                return o.toString();
            }
        };
    }
}
```

> Error: [dereference.of.nullable] dereference of possibly-null reference o | Line 15 | Column 70

Reproduced using above code on http://eisop.uwaterloo.ca/live

**Comment by smillst** [comment] 2017-08-16 18:49
The null check, ` if (o == null) throw new NullPointerException();` and using `@RequiresNonNull`, don't help, because the refinement of `o` to `@NonNull` isn't passed into the anonymous class.  This issue has been reported before and is tracked in https://github.com/typetools/checker-framework/issues/266.

It seems like this issue is a duplicate of #266 and should be closed in favor of that issue, but since the title of this issue is "Support for Guava Suppliers", I'm not sure if that's true.  Is there something else required to support suppliers?

**Comment by rcchan** [comment] 2017-08-16 20:50
Should `get()` be able to assume that `final Object o` (implied `@NonNull`) can't be null when it's called?  Should nullness be evaluated at the point that the inner class method is actually called instead of where it's defined?

- If we try to call it in the constructor, the supplier itself can't be assumed non-null since it will still be `UnderInitialization`.  That would already require an additional annotation.  Also, we don't do this (can checker tell?)
- If it's called outside the constructor, `o` must have already been initialized to non-null.

**Comment by rcchan** [comment] 2017-08-16 20:51
I don't think `Supplier` requires any additional magic beyond what any generic `Callback { T method() { ... } }` would.

**Comment by smillst** [comment] 2017-08-16 21:26
In general, I would annotate the code (and work around #266) as follows:
```
class Foo {
    private final Object o;
    private final Supplier<String> s;
    Foo() {
        o = new Object();
        s = a();
    }
    @RequiresNonNull("o")
    private Supplier<String> a(@UnderInitialization Foo this) {
        return new Supplier<String>() {  
            public String get() {
                @SuppressWarnings("nullness") // o must be nonnull because of precondition of a
                @NonNull Object nonNullO = o; 
                return nonNullO.toString();
            }
        };
    }
}
```
But I'm going to answer your questions using the version of your example that would still issue an error even if #266 was implement.  Specifically, this code:
```
class Foo {
    private final Object o;
    private final Supplier<String> s;
    Foo() {
        o = new Object();
        s = a();
    }
    
    private Supplier<String> a(@UnderInitialization Foo this) {
        return new Supplier<String>() {  
            public String get() {
                return o.toString();  // error 
            }
        };
    }
}
```

>Should `get()` be able to assume that `final Object o` (implied `@NonNull`) can't be null when it's called? Should nullness be evaluated at the point that the inner class method is actually called instead of where it's defined?

No, the "nullness" of a body of a method is decided where it is declared.   `get` can't assume that `o` is `@NonNull` because, by marking the receiver of `a` as `@UnderInitialization`, you have stated that `a` and `get` may be called in places where `o` and all the fields of `Foo` have not been initialized. For example, the constructor could have been written as:
```
    Foo() {
        s = a();
        s.get();  // null pointer exception because `o` is null, but no Nullness Checker error
        o = new Object();
    }
```
However, if you added `@RequiresNonNull("o") ` to the declaration of `a`, then `get` could assume that `o` is `@NonNull`.   (This isn't implement, see #266.)  In that case, the Nullness Checker would issue an error at the call to `a()` above.

>- If we try to call it in the constructor, the supplier itself can't be assumed non-null since it will still be `UnderInitialization`.  That would already require an additional annotation.  Also, we don't do this (can checker tell?)

This wouldn't require an extra annotation as shown in the above code.  When type checking a method a checker doesn't know where or under what context the method is called.  Unless the method declaration includes some precondition such as `@RequiresNonNull("o")`

**Comment by rcchan** [comment] 2017-08-17 17:28
Thanks for the information!

One interesting thing I noticed while implementing your suggestion: returning a `Supplier` by using `return () -> o.toString()` doesn't require the `@SuppressWarnings` while using `new Supplier() { ... }` does.  I guess these aren't equivalent?

**Comment by smillst** [comment] 2017-08-17 19:58
No, but note that if `o` was a local variable in `a`, then the warning would still happen because of #1248.

**Comment by smillst** [comment] 2017-08-17 19:59
I'm going to close this issue since it is a duplicate of #266.

**Closed by smillst** 2017-08-17 19:59 UTC
