### ISSUE TITLE
Optional.ofNullable

### ISSUE THREAD

**Issue by urbandroid** [typetools/checker-framework#1760] opened 2018-01-14 03:28 UTC
```
    
private @Nullable String user;

public Optional<String> getUser() {
        return Optional.ofNullable(user);
    }
```

Error:(20, 35) java: [return.type.incompatible] incompatible types in return.
  found   : @Initialized @NonNull Optional<@Initialized @Nullable String>
  required: @Initialized @NonNull Optional<@Initialized @NonNull String>

clearly Optional.ofNullable(user) not going to return null it will either return Optional box with string in it or a Optional box which has Optional.empty . 
Why does this error is shown? And also it is not accepting this  anotation either:

```
 public Optional<@Nullable String> getUser() {
        return Optional.ofNullable(user);
    }
```
What are my options?

**Comment by urbandroid** [comment] 2018-01-14 23:24
i'm using javax.annotation.Nullable of   

```
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
        </dependency>
```
with 

```
                <dependency>
                    <groupId>org.checkerframework</groupId>
                    <artifactId>checker</artifactId>
                    <version>1.9.13</version>
                    <scope>provided</scope>
                </dependency>
```
I'm using open jdk 1.8.0 not a modified jdk with maven. Which is working correctly except for this case.

**Comment by wmdietl** [comment] 2018-01-15 00:09
Are you following the instructions at https://checkerframework.org/manual/#maven
Do you include:

```xml
    <dependency>
      <groupId>org.checkerframework</groupId>
      <artifactId>jdk8</artifactId>
      <version>2.3.1</version>
    </dependency>
```

and pass it as `<arg>-Xbootclasspath/p:${annotatedJdk}</arg>`?

If you don't use the annotated JDK as described in the instructions, you will not get the specifications, in this case the specifications from https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/util/Optional.java

Without these specifications your errors are expected.

**Comment by urbandroid** [comment] 2018-01-16 05:04
@wmdietl here is updated profile:

```
       <profile>
            <id>checker</id>
            <properties>
                <!-- These properties will be set by the Maven Dependency plugin -->
                <annotatedJdk>${org.checkerframework:jdk8:jar}</annotatedJdk>
                <!-- Uncomment to use the Type Annotations compiler. -->
                <!-- <typeAnnotationsJavac>${org.checkerframework:compiler:jar}</typeAnnotationsJavac> -->
            </properties>
            <dependencies>
                <dependency>
                    <groupId>org.checkerframework</groupId>
                    <artifactId>checker</artifactId>
                    <version>2.3.1</version>
                </dependency>
                <dependency>
                    <groupId>org.checkerframework</groupId>
                    <artifactId>jdk8</artifactId>
                    <version>2.3.1</version>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>2.10</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>properties</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.6.1</version>
                        <configuration>
                            <source>1.8</source>
                            <target>1.8</target>
                            <annotationProcessors>
                                <annotationProcessor>org.checkerframework.checker.nullness.NullnessChecker
                                </annotationProcessor>
                            </annotationProcessors>
                            <compilerArgs>
                                <arg>-Xbootclasspath/p:${annotatedJdk}</arg>
                                <!--<arg>-Xbootclasspath/p:${org.checkerframework:jdk8:jar}</arg>-->
                            </compilerArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

error i mentioned earlier persists. nothing changed.

**Comment by smillst** [comment] 2018-01-16 19:25
We can't reproduce your issue from the command line, so the problem has to be with your Maven setup.   The snippet of your pom file above doesn't follow the instructions in the Checker Framework manual.  In particular, you are using a profile.   I would guess that you can't use the `build` element in `profiles`.  If you need further help debugging your issue, please provide us a way to reproduce it.  Thanks!

**Comment by urbandroid** [comment] 2018-01-17 04:23
@smillst What is wrong with my Maven setup?

**Comment by mernst** [comment] 2018-01-24 16:53
I'm closing this for now, but if someone can reproduce the problem, we are happy to investigate it.

**Closed by mernst** 2018-01-24 16:53 UTC
Labels: Unreproducible

**Comment by urbandroid** [comment] 2018-02-21 21:52
`ServerDetails` added.
