### ISSUE TITLE
StackOverflowError caused by an array literal of generics

### ISSUE THREAD

**Issue by pallosp** [typetools/checker-framework#721] opened 2016-05-13 12:13 UTC
The following code snippet causes a StackOverflowError in the checker framework:

<pre>
interface I {}
interface J {}
interface K&lt;T extends J> extends I {}
&lt;T extends J> K&lt;T> f() {
  return new K&lt;T>() {};
}
I[] i = new I[] { f() };
</pre>

Stack trace:

Exception: java.lang.StackOverflowError; Stack trace: org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.methodFromUse(NullnessAnnotatedTypeFactory.java:238)
org.checkerframework.framework.type.TypeFromTree$TypeFromExpression.visitMethodInvocation(TypeFromTree.java:260)
org.checkerframework.framework.type.TypeFromTree$TypeFromExpression.visitMethodInvocation(TypeFromTree.java:104)
com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
org.checkerframework.framework.type.AnnotatedTypeFactory.fromTreeWithVisitor(AnnotatedTypeFactory.java:885)
org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:807)
org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:617)
org.checkerframework.framework.type.PropagationTreeAnnotator.visitNewArray(PropagationTreeAnnotator.java:73)
org.checkerframework.framework.type.PropagationTreeAnnotator.visitNewArray(PropagationTreeAnnotator.java:47)
com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1574)
com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
org.checkerframework.framework.type.ListTreeAnnotator.defaultAction(ListTreeAnnotator.java:36)
org.checkerframework.framework.type.ListTreeAnnotator.defaultAction(ListTreeAnnotator.java:19)
com.sun.source.util.SimpleTreeVisitor.visitNewArray(SimpleTreeVisitor.java:173)
com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1574)
com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:816)
org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.annotateImplicit(NullnessAnnotatedTypeFactory.java:167)
org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:797)

...

org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:816)
org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.annotateImplicit(NullnessAnnotatedTypeFactory.java:167)
org.checkerframework.framework.type.GenericAnnotatedTypeFactory.annotateImplicit(GenericAnnotatedTypeFactory.java:797)
org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:624)
org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1697)
org.checkerframework.framework.util.AnnotatedTypes.assignedTo(AnnotatedTypes.java:1023)
org.checkerframework.framework.util.AnnotatedTypes.inferTypeArguments(AnnotatedTypes.java:708)
org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:657)
org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1460)
org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1446)
org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:911)
org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.methodFromUse(NullnessAnnotatedTypeFactory.java:239)
org.checkerframework.framework.type.TypeFromTree$TypeFromExpression.visitMethodInvocation(TypeFromTree.java:260)
org.checkerframework.framework.type.TypeFromTree$TypeFromExpression.visitMethodInvocation(TypeFromTree.java:104)
com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
org.checkerframework.framework.type.AnnotatedTypeFactory.fromTreeWithVisitor(AnnotatedTypeFactory.java:885)
org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:807)
org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:617)
org.checkerframework.framework.type.PropagationTreeAnnotator.visitNewArray(PropagationTreeAnnotator.java:73)
org.checkerframework.framework.type.PropagationTreeAnnotator.visitNewArray(PropagationTreeAnnotator.java:47)
com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1574)
com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
org.checkerframework.framework.type.ListTreeAnnotator.defaultAction(ListTreeAnnotator.java:36)
org.checkerframework.framework.type.ListTreeAnnotator.defaultAction(ListTreeAnnotator.java:19)
com.sun.source.util.SimpleTreeVisitor.visitNewArray(SimpleTreeVisitor.java:173)
com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1574)

**Comment by pallosp** [comment] 2016-05-13 12:17
Github ate my angle brackets.
The correct code snippet is:

<pre>
interface I {}
interface J {}
interface K&lt;T extends J> extends I {}
&lt;T extends J> K&lt;T> f() {
  return new K&lt;T>() {};
}
I[] i = new I[] { f() };
</pre>

**Comment by mernst** [comment] 2016-05-13 16:03
I cannot reproduce this problem.  You didn't provide a complete test case, but I completed in in the following way:

```
public class Issue721 {

  interface I {}
  interface J {}
  interface K<T extends J> extends I {}
  <T extends J> K<T> f() {
    return new K<T>() {};
  }

  void m() {
    I[] i = new I[] { f() };
  }
}
```

When I ran the Nullness Checker on this code with `cheker/bin/javac -processor nullness Issue721.java`, it did not throw an exception.  I tried other variants, too, such as 

```
interface I {}
interface J {}
interface K<T extends J> extends I {}

public class Issue721 {

  <T extends J> K<T> f() {
    return new K<T>() {};
  }

  void m() {
    I[] i = new I[] { f() };
  }
}
```

I'm closing the issue, but if you can provide a complete, reproducible test case, we will reopen it.  Thanks!

**Closed by mernst** 2016-05-13 16:03 UTC

**Comment by pallosp** [comment] 2016-05-17 11:54
The Issue721 class still reproduces the StackOverflowError when it runs through Google's build system. We're using version 1.8.0-jsr308-1.8.11 with the following parameters:

-Xbootclasspath/p:third_party/java/checker_framework/jdk.sym
-XDallowTypeAnnotationsInComments
-source 7
-target 7
-encoding utf8
-AprintErrorStack
-AskipUses=^org\.
-AskipUses=^sun\.
-processor org.checkerframework.checker.nullness.NullnessChecker
-proc:only
-Astubs=java/com/google/devtools/staticanalysis/java/checker/stubs
-XDTA:spacesincomments
-Xmaxerrs 10000
-AsuppressWarnings=purity.invalid.overriding,keyfor
-sourcepath :
-processorpath java/com/google/devtools/staticanalysis/java/checker/checker_deploy.jar
-cp <couple of android jars>:java/com/google/devtools/staticanalysis/java/checker/checker_deploy.jar
Issue721.java

I'm still trying to configure Checker Framework 2.0.0 to use the same processor to find out whether the  StackOverflowError has been fixed.

**Comment by mernst** [comment] 2016-05-17 14:46
I'm sorry you are having trouble, but thanks for getting in touch with us.

Version 1.8.11 is over a year old, and we have resolved 91 issues since it was released.  It is possible that the problem you are encountering has been fixed in the intervening 15 releases of the Checker Framework.

I tried again with a slight variation of your your command line that removes Google-specific command-line arguments:

```$ch/bin/javac -XDallowTypeAnnotationsInComments -source 7 -target 7 -encoding utf8 -AprintErrorStack -AskipUses=^org.  -AskipUses=^sun.  -processor org.checkerframework.checker.nullness.NullnessChecker -proc:only -XDTA:spacesincomments -Xmaxerrs 10000 -AsuppressWarnings=purity.invalid.overriding,keyfor -sourcepath : Issue721.java```

and I still cannot reproduce the problem.

Liam Miller-Cushon should be able to help you configure Google's build system to use a more recent version of the Checker Framework.

Please get back in touch if you encounter any more problems.

**Comment by pallosp** [comment] 2016-06-09 07:49
I confirm that 2.0.0 no longer has this bug.
