### ISSUE TITLE
giving same error 2 times

### ISSUE THREAD

**Issue by shivanshsoni** [typetools/checker-framework#1124] opened 2017-03-10 09:28 UTC
Why it is giving same error 2 times with same location. 

My code was:

![screenshot 11](https://cloud.githubusercontent.com/assets/24546371/23789671/df7b3c88-05a1-11e7-8c62-13b8c1d28b4a.png)

error on cmd:

![screenshot 10](https://cloud.githubusercontent.com/assets/24546371/23789714/0247eef0-05a2-11e7-855f-9a4bf31344c0.png)

**Comment by mernst** [comment] 2017-03-10 16:22
This issue is a duplicate of issue #1051.
There is already a pull request open, #1106.

**Closed by mernst** 2017-03-10 16:22 UTC
