### ISSUE TITLE
Exception during nullness checking of stream items

### ISSUE THREAD

**Issue by twistedsquare** [typetools/checker-framework#1006] opened 2017-01-05 20:18 UTC
Here's a minimal version of the problematic code:

```
import java.util.function.Function;
import java.util.stream.*;
import java.util.*;

public class StreamProblem
{
    public static Map<String, Long> getFreq(String src)
    {
        return Stream.of(src).collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
    }	
}
```

Compiling with the nullness processor (version 2.1.7) gives an exception in the checker:
```
javac -cp checker-2.1.7.jar -processor org.checkerframework.checker.nullness.NullnessChecker -AprintErrorStack StreamProblem.java
error: AsSuperVisitor: Unexpected combination: type: NULL superType: NULL.
  type:  null
  superType:  null
  Compilation unit: StreamProblem.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:721)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:44)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitNull_Null(AbstractAtmComboVisitor.java:377)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:514)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:50)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.util.AtmLubVisitor.lubWithNull(AtmLubVisitor.java:70)
  org.checkerframework.framework.util.AtmLubVisitor.lub(AtmLubVisitor.java:53)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:638)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:619)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.handleNullTypeArguments(DefaultTypeArgumentInference.java:169)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferTypeArgs(DefaultTypeArgumentInference.java:119)
  org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:586)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1816)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1800)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1291)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:179)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:47)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1185)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:959)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:202)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:881)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:49)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:24)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:79)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:382)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:203)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1022)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:979)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:909)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1240)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:215)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:278)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:164)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:947)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:443)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:437)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
error: AsSuperVisitor: Unexpected combination: type: NULL superType: NULL.
  type: null
  superType: null
  Compilation unit: StreamProblem.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:721)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:44)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitNull_Null(AbstractAtmComboVisitor.java:377)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:514)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:50)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:86)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:68)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:131)
  org.checkerframework.framework.util.AtmLubVisitor.lubWithNull(AtmLubVisitor.java:70)
  org.checkerframework.framework.util.AtmLubVisitor.lub(AtmLubVisitor.java:53)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:638)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:619)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.handleNullTypeArguments(DefaultTypeArgumentInference.java:169)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferTypeArgs(DefaultTypeArgumentInference.java:119)
  org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:586)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1816)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1800)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1291)
  org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.methodFromUse(NullnessAnnotatedTypeFactory.java:300)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:179)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:47)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1185)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:959)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:202)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:881)
  org.checkerframework.checker.initialization.InitializationTransfer.visitMethodInvocation(InitializationTransfer.java:196)
  org.checkerframework.checker.nullness.NullnessTransfer.visitMethodInvocation(NullnessTransfer.java:210)
  org.checkerframework.checker.nullness.NullnessTransfer.visitMethodInvocation(NullnessTransfer.java:51)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:79)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:382)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:203)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1022)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:979)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:909)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1240)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:215)
  org.checkerframework.checker.initialization.InitializationVisitor.visitClass(InitializationVisitor.java:274)
  org.checkerframework.checker.initialization.InitializationVisitor.visitClass(InitializationVisitor.java:57)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:947)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:443)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
2 errors
1 warning
```

Explicitly typing the identity and counting functions seems to avoid the problem, but thought I'd report it.

**Comment by wmdietlGC** [comment] 2017-02-14 00:53
I recently also ran into this issue. I've added a test case https://github.com/wmdietlGC/checker-framework/commit/84ea78732d1aa2a626d7af4d9acd274c7fe98cb6 , which I'll make a PR for once https://github.com/typetools/checker-framework/pull/1038 was merged.

**Comment by wmdietlGC** [comment] 2017-02-14 18:24
https://github.com/typetools/checker-framework/pull/1041

**Comment by wmdietlGC** [comment] 2017-02-27 22:02
The following patch works around the exception, but results in false positive errors:

```
diff --git a/framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java b/framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
index 544074bbd..adf35fc87 100644
--- a/framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
+++ b/framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
@@ -160,7 +160,7 @@ public class DefaultTypeArgumentInference implements TypeArgumentInference {
                 }
             } else if (result.getKind() == TypeKind.NULL) {
                 AnnotatedTypeMirror withoutNullResult = inferredArgsWithOutNull.get(typeVar);
-                if (withoutNullResult == null) {
+                if (withoutNullResult == null || withoutNullResult.getKind() == TypeKind.NULL) {
                     // withoutNullResult is null when the only constraint on a type argument is
                     // where a method argument is null.
                     withoutNullResult = typeFactory.getUninferredWildcardType(atv);
```

The comment within that `if` branch doesn't really apply, because there are no `null`s in the test case.
So maybe this isn't a good fix.

@smillst what do you think?

**Comment by smillst** [comment] 2017-02-27 22:32
@wmdietlGC I just posted a pull request (#1086) that fixes this crash.  This crash is caused by a bug in lub.  Once, I fixed that crash, 2 more crash appeared, which I also fixed.

**Closed** 2017-02-28 23:10 UTC
Labels: crash
